// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="ov5640_GaussianBlur,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg400-2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=10.674000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=9,HLS_SYN_DSP=12,HLS_SYN_FF=2361,HLS_SYN_LUT=3265,HLS_VERSION=2018_3}" *)

module ov5640_GaussianBlur (
        INPUT_STREAM_TDATA,
        INPUT_STREAM_TKEEP,
        INPUT_STREAM_TSTRB,
        INPUT_STREAM_TUSER,
        INPUT_STREAM_TLAST,
        INPUT_STREAM_TID,
        INPUT_STREAM_TDEST,
        OUTPUT_STREAM_TDATA,
        OUTPUT_STREAM_TKEEP,
        OUTPUT_STREAM_TSTRB,
        OUTPUT_STREAM_TUSER,
        OUTPUT_STREAM_TLAST,
        OUTPUT_STREAM_TID,
        OUTPUT_STREAM_TDEST,
        ap_clk,
        ap_rst_n,
        INPUT_STREAM_TVALID,
        INPUT_STREAM_TREADY,
        OUTPUT_STREAM_TVALID,
        OUTPUT_STREAM_TREADY
);


input  [23:0] INPUT_STREAM_TDATA;
input  [2:0] INPUT_STREAM_TKEEP;
input  [2:0] INPUT_STREAM_TSTRB;
input  [0:0] INPUT_STREAM_TUSER;
input  [0:0] INPUT_STREAM_TLAST;
input  [0:0] INPUT_STREAM_TID;
input  [0:0] INPUT_STREAM_TDEST;
output  [23:0] OUTPUT_STREAM_TDATA;
output  [2:0] OUTPUT_STREAM_TKEEP;
output  [2:0] OUTPUT_STREAM_TSTRB;
output  [0:0] OUTPUT_STREAM_TUSER;
output  [0:0] OUTPUT_STREAM_TLAST;
output  [0:0] OUTPUT_STREAM_TID;
output  [0:0] OUTPUT_STREAM_TDEST;
input   ap_clk;
input   ap_rst_n;
input   INPUT_STREAM_TVALID;
output   INPUT_STREAM_TREADY;
output   OUTPUT_STREAM_TVALID;
input   OUTPUT_STREAM_TREADY;

 reg    ap_rst_n_inv;
wire    Block_proc_U0_ap_start;
wire    Block_proc_U0_ap_done;
wire    Block_proc_U0_ap_continue;
wire    Block_proc_U0_ap_idle;
wire    Block_proc_U0_ap_ready;
wire    Block_proc_U0_start_out;
wire    Block_proc_U0_start_write;
wire   [9:0] Block_proc_U0_img_0_rows_V_out_din;
wire    Block_proc_U0_img_0_rows_V_out_write;
wire   [10:0] Block_proc_U0_img_0_cols_V_out_din;
wire    Block_proc_U0_img_0_cols_V_out_write;
wire   [9:0] Block_proc_U0_img_1_rows_V_out_din;
wire    Block_proc_U0_img_1_rows_V_out_write;
wire   [10:0] Block_proc_U0_img_1_cols_V_out_din;
wire    Block_proc_U0_img_1_cols_V_out_write;
wire    AXIvideo2Mat_U0_ap_start;
wire    AXIvideo2Mat_U0_ap_done;
wire    AXIvideo2Mat_U0_ap_continue;
wire    AXIvideo2Mat_U0_ap_idle;
wire    AXIvideo2Mat_U0_ap_ready;
wire    AXIvideo2Mat_U0_start_out;
wire    AXIvideo2Mat_U0_start_write;
wire    AXIvideo2Mat_U0_INPUT_STREAM_TREADY;
wire    AXIvideo2Mat_U0_img_rows_V_read;
wire    AXIvideo2Mat_U0_img_cols_V_read;
wire   [7:0] AXIvideo2Mat_U0_img_data_stream_0_V_din;
wire    AXIvideo2Mat_U0_img_data_stream_0_V_write;
wire   [7:0] AXIvideo2Mat_U0_img_data_stream_1_V_din;
wire    AXIvideo2Mat_U0_img_data_stream_1_V_write;
wire   [7:0] AXIvideo2Mat_U0_img_data_stream_2_V_din;
wire    AXIvideo2Mat_U0_img_data_stream_2_V_write;
wire   [9:0] AXIvideo2Mat_U0_img_rows_V_out_din;
wire    AXIvideo2Mat_U0_img_rows_V_out_write;
wire   [10:0] AXIvideo2Mat_U0_img_cols_V_out_din;
wire    AXIvideo2Mat_U0_img_cols_V_out_write;
wire    Split_U0_ap_start;
wire    Split_U0_start_full_n;
wire    Split_U0_ap_done;
wire    Split_U0_ap_continue;
wire    Split_U0_ap_idle;
wire    Split_U0_ap_ready;
wire    Split_U0_start_out;
wire    Split_U0_start_write;
wire    Split_U0_src_rows_V_read;
wire    Split_U0_src_cols_V_read;
wire    Split_U0_src_data_stream_0_V_read;
wire    Split_U0_src_data_stream_1_V_read;
wire    Split_U0_src_data_stream_2_V_read;
wire   [7:0] Split_U0_dst0_data_stream_V_din;
wire    Split_U0_dst0_data_stream_V_write;
wire   [7:0] Split_U0_dst1_data_stream_V_din;
wire    Split_U0_dst1_data_stream_V_write;
wire   [7:0] Split_U0_dst2_data_stream_V_din;
wire    Split_U0_dst2_data_stream_V_write;
wire    GaussianBlur162_U0_ap_start;
wire    GaussianBlur162_U0_ap_done;
wire    GaussianBlur162_U0_ap_continue;
wire    GaussianBlur162_U0_ap_idle;
wire    GaussianBlur162_U0_ap_ready;
wire    GaussianBlur162_U0_p_src_data_stream_V_read;
wire   [7:0] GaussianBlur162_U0_p_dst_data_stream_V_din;
wire    GaussianBlur162_U0_p_dst_data_stream_V_write;
wire    GaussianBlur163_U0_ap_start;
wire    GaussianBlur163_U0_ap_done;
wire    GaussianBlur163_U0_ap_continue;
wire    GaussianBlur163_U0_ap_idle;
wire    GaussianBlur163_U0_ap_ready;
wire    GaussianBlur163_U0_p_src_data_stream_V_read;
wire   [7:0] GaussianBlur163_U0_p_dst_data_stream_V_din;
wire    GaussianBlur163_U0_p_dst_data_stream_V_write;
wire    GaussianBlur_U0_ap_start;
wire    GaussianBlur_U0_ap_done;
wire    GaussianBlur_U0_ap_continue;
wire    GaussianBlur_U0_ap_idle;
wire    GaussianBlur_U0_ap_ready;
wire    GaussianBlur_U0_p_src_data_stream_V_read;
wire   [7:0] GaussianBlur_U0_p_dst_data_stream_V_din;
wire    GaussianBlur_U0_p_dst_data_stream_V_write;
wire    Merge_U0_ap_start;
wire    Merge_U0_ap_done;
wire    Merge_U0_ap_continue;
wire    Merge_U0_ap_idle;
wire    Merge_U0_ap_ready;
wire    Merge_U0_start_out;
wire    Merge_U0_start_write;
wire    Merge_U0_src0_data_stream_V_read;
wire    Merge_U0_src1_data_stream_V_read;
wire    Merge_U0_src2_data_stream_V_read;
wire    Merge_U0_dst_rows_V_read;
wire    Merge_U0_dst_cols_V_read;
wire   [7:0] Merge_U0_dst_data_stream_0_V_din;
wire    Merge_U0_dst_data_stream_0_V_write;
wire   [7:0] Merge_U0_dst_data_stream_1_V_din;
wire    Merge_U0_dst_data_stream_1_V_write;
wire   [7:0] Merge_U0_dst_data_stream_2_V_din;
wire    Merge_U0_dst_data_stream_2_V_write;
wire   [9:0] Merge_U0_dst_rows_V_out_din;
wire    Merge_U0_dst_rows_V_out_write;
wire   [10:0] Merge_U0_dst_cols_V_out_din;
wire    Merge_U0_dst_cols_V_out_write;
wire    Mat2AXIvideo_U0_ap_start;
wire    Mat2AXIvideo_U0_ap_done;
wire    Mat2AXIvideo_U0_ap_continue;
wire    Mat2AXIvideo_U0_ap_idle;
wire    Mat2AXIvideo_U0_ap_ready;
wire    Mat2AXIvideo_U0_img_rows_V_read;
wire    Mat2AXIvideo_U0_img_cols_V_read;
wire    Mat2AXIvideo_U0_img_data_stream_0_V_read;
wire    Mat2AXIvideo_U0_img_data_stream_1_V_read;
wire    Mat2AXIvideo_U0_img_data_stream_2_V_read;
wire   [23:0] Mat2AXIvideo_U0_OUTPUT_STREAM_TDATA;
wire    Mat2AXIvideo_U0_OUTPUT_STREAM_TVALID;
wire   [2:0] Mat2AXIvideo_U0_OUTPUT_STREAM_TKEEP;
wire   [2:0] Mat2AXIvideo_U0_OUTPUT_STREAM_TSTRB;
wire   [0:0] Mat2AXIvideo_U0_OUTPUT_STREAM_TUSER;
wire   [0:0] Mat2AXIvideo_U0_OUTPUT_STREAM_TLAST;
wire   [0:0] Mat2AXIvideo_U0_OUTPUT_STREAM_TID;
wire   [0:0] Mat2AXIvideo_U0_OUTPUT_STREAM_TDEST;
wire    ap_sync_continue;
wire    img_0_rows_V_c_full_n;
wire   [9:0] img_0_rows_V_c_dout;
wire    img_0_rows_V_c_empty_n;
wire    img_0_cols_V_c_full_n;
wire   [10:0] img_0_cols_V_c_dout;
wire    img_0_cols_V_c_empty_n;
wire    img_1_rows_V_c_full_n;
wire   [9:0] img_1_rows_V_c_dout;
wire    img_1_rows_V_c_empty_n;
wire    img_1_cols_V_c_full_n;
wire   [10:0] img_1_cols_V_c_dout;
wire    img_1_cols_V_c_empty_n;
wire    img_0_data_stream_0_full_n;
wire   [7:0] img_0_data_stream_0_dout;
wire    img_0_data_stream_0_empty_n;
wire    img_0_data_stream_1_full_n;
wire   [7:0] img_0_data_stream_1_dout;
wire    img_0_data_stream_1_empty_n;
wire    img_0_data_stream_2_full_n;
wire   [7:0] img_0_data_stream_2_dout;
wire    img_0_data_stream_2_empty_n;
wire    img_0_rows_V_c20_full_n;
wire   [9:0] img_0_rows_V_c20_dout;
wire    img_0_rows_V_c20_empty_n;
wire    img_0_cols_V_c21_full_n;
wire   [10:0] img_0_cols_V_c21_dout;
wire    img_0_cols_V_c21_empty_n;
wire    img_B_data_stream_0_full_n;
wire   [7:0] img_B_data_stream_0_dout;
wire    img_B_data_stream_0_empty_n;
wire    img_G_data_stream_0_full_n;
wire   [7:0] img_G_data_stream_0_dout;
wire    img_G_data_stream_0_empty_n;
wire    img_R_data_stream_0_full_n;
wire   [7:0] img_R_data_stream_0_dout;
wire    img_R_data_stream_0_empty_n;
wire    img_B_f_data_stream_s_full_n;
wire   [7:0] img_B_f_data_stream_s_dout;
wire    img_B_f_data_stream_s_empty_n;
wire    img_G_f_data_stream_s_full_n;
wire   [7:0] img_G_f_data_stream_s_dout;
wire    img_G_f_data_stream_s_empty_n;
wire    img_R_f_data_stream_s_full_n;
wire   [7:0] img_R_f_data_stream_s_dout;
wire    img_R_f_data_stream_s_empty_n;
wire    img_1_data_stream_0_full_n;
wire   [7:0] img_1_data_stream_0_dout;
wire    img_1_data_stream_0_empty_n;
wire    img_1_data_stream_1_full_n;
wire   [7:0] img_1_data_stream_1_dout;
wire    img_1_data_stream_1_empty_n;
wire    img_1_data_stream_2_full_n;
wire   [7:0] img_1_data_stream_2_dout;
wire    img_1_data_stream_2_empty_n;
wire    img_1_rows_V_c22_full_n;
wire   [9:0] img_1_rows_V_c22_dout;
wire    img_1_rows_V_c22_empty_n;
wire    img_1_cols_V_c23_full_n;
wire   [10:0] img_1_cols_V_c23_dout;
wire    img_1_cols_V_c23_empty_n;
wire   [0:0] start_for_Merge_U0_din;
wire    start_for_Merge_U0_full_n;
wire   [0:0] start_for_Merge_U0_dout;
wire    start_for_Merge_U0_empty_n;
wire   [0:0] start_for_Split_U0_din;
wire    start_for_Split_U0_full_n;
wire   [0:0] start_for_Split_U0_dout;
wire    start_for_Split_U0_empty_n;
wire   [0:0] start_for_GaussianBlur162_U0_din;
wire    start_for_GaussianBlur162_U0_full_n;
wire   [0:0] start_for_GaussianBlur162_U0_dout;
wire    start_for_GaussianBlur162_U0_empty_n;
wire   [0:0] start_for_GaussianBlur163_U0_din;
wire    start_for_GaussianBlur163_U0_full_n;
wire   [0:0] start_for_GaussianBlur163_U0_dout;
wire    start_for_GaussianBlur163_U0_empty_n;
wire   [0:0] start_for_GaussianBlur_U0_din;
wire    start_for_GaussianBlur_U0_full_n;
wire   [0:0] start_for_GaussianBlur_U0_dout;
wire    start_for_GaussianBlur_U0_empty_n;
wire    GaussianBlur162_U0_start_full_n;
wire    GaussianBlur162_U0_start_write;
wire    GaussianBlur163_U0_start_full_n;
wire    GaussianBlur163_U0_start_write;
wire    GaussianBlur_U0_start_full_n;
wire    GaussianBlur_U0_start_write;
wire   [0:0] start_for_Mat2AXIvideo_U0_din;
wire    start_for_Mat2AXIvideo_U0_full_n;
wire   [0:0] start_for_Mat2AXIvideo_U0_dout;
wire    start_for_Mat2AXIvideo_U0_empty_n;
wire    Mat2AXIvideo_U0_start_full_n;
wire    Mat2AXIvideo_U0_start_write;

Block_proc Block_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Block_proc_U0_ap_start),
    .start_full_n(start_for_Merge_U0_full_n),
    .ap_done(Block_proc_U0_ap_done),
    .ap_continue(Block_proc_U0_ap_continue),
    .ap_idle(Block_proc_U0_ap_idle),
    .ap_ready(Block_proc_U0_ap_ready),
    .start_out(Block_proc_U0_start_out),
    .start_write(Block_proc_U0_start_write),
    .img_0_rows_V_out_din(Block_proc_U0_img_0_rows_V_out_din),
    .img_0_rows_V_out_full_n(img_0_rows_V_c_full_n),
    .img_0_rows_V_out_write(Block_proc_U0_img_0_rows_V_out_write),
    .img_0_cols_V_out_din(Block_proc_U0_img_0_cols_V_out_din),
    .img_0_cols_V_out_full_n(img_0_cols_V_c_full_n),
    .img_0_cols_V_out_write(Block_proc_U0_img_0_cols_V_out_write),
    .img_1_rows_V_out_din(Block_proc_U0_img_1_rows_V_out_din),
    .img_1_rows_V_out_full_n(img_1_rows_V_c_full_n),
    .img_1_rows_V_out_write(Block_proc_U0_img_1_rows_V_out_write),
    .img_1_cols_V_out_din(Block_proc_U0_img_1_cols_V_out_din),
    .img_1_cols_V_out_full_n(img_1_cols_V_c_full_n),
    .img_1_cols_V_out_write(Block_proc_U0_img_1_cols_V_out_write)
);

AXIvideo2Mat AXIvideo2Mat_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(AXIvideo2Mat_U0_ap_start),
    .start_full_n(start_for_Split_U0_full_n),
    .ap_done(AXIvideo2Mat_U0_ap_done),
    .ap_continue(AXIvideo2Mat_U0_ap_continue),
    .ap_idle(AXIvideo2Mat_U0_ap_idle),
    .ap_ready(AXIvideo2Mat_U0_ap_ready),
    .start_out(AXIvideo2Mat_U0_start_out),
    .start_write(AXIvideo2Mat_U0_start_write),
    .INPUT_STREAM_TDATA(INPUT_STREAM_TDATA),
    .INPUT_STREAM_TVALID(INPUT_STREAM_TVALID),
    .INPUT_STREAM_TREADY(AXIvideo2Mat_U0_INPUT_STREAM_TREADY),
    .INPUT_STREAM_TKEEP(INPUT_STREAM_TKEEP),
    .INPUT_STREAM_TSTRB(INPUT_STREAM_TSTRB),
    .INPUT_STREAM_TUSER(INPUT_STREAM_TUSER),
    .INPUT_STREAM_TLAST(INPUT_STREAM_TLAST),
    .INPUT_STREAM_TID(INPUT_STREAM_TID),
    .INPUT_STREAM_TDEST(INPUT_STREAM_TDEST),
    .img_rows_V_dout(img_0_rows_V_c_dout),
    .img_rows_V_empty_n(img_0_rows_V_c_empty_n),
    .img_rows_V_read(AXIvideo2Mat_U0_img_rows_V_read),
    .img_cols_V_dout(img_0_cols_V_c_dout),
    .img_cols_V_empty_n(img_0_cols_V_c_empty_n),
    .img_cols_V_read(AXIvideo2Mat_U0_img_cols_V_read),
    .img_data_stream_0_V_din(AXIvideo2Mat_U0_img_data_stream_0_V_din),
    .img_data_stream_0_V_full_n(img_0_data_stream_0_full_n),
    .img_data_stream_0_V_write(AXIvideo2Mat_U0_img_data_stream_0_V_write),
    .img_data_stream_1_V_din(AXIvideo2Mat_U0_img_data_stream_1_V_din),
    .img_data_stream_1_V_full_n(img_0_data_stream_1_full_n),
    .img_data_stream_1_V_write(AXIvideo2Mat_U0_img_data_stream_1_V_write),
    .img_data_stream_2_V_din(AXIvideo2Mat_U0_img_data_stream_2_V_din),
    .img_data_stream_2_V_full_n(img_0_data_stream_2_full_n),
    .img_data_stream_2_V_write(AXIvideo2Mat_U0_img_data_stream_2_V_write),
    .img_rows_V_out_din(AXIvideo2Mat_U0_img_rows_V_out_din),
    .img_rows_V_out_full_n(img_0_rows_V_c20_full_n),
    .img_rows_V_out_write(AXIvideo2Mat_U0_img_rows_V_out_write),
    .img_cols_V_out_din(AXIvideo2Mat_U0_img_cols_V_out_din),
    .img_cols_V_out_full_n(img_0_cols_V_c21_full_n),
    .img_cols_V_out_write(AXIvideo2Mat_U0_img_cols_V_out_write)
);

Split Split_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Split_U0_ap_start),
    .start_full_n(Split_U0_start_full_n),
    .ap_done(Split_U0_ap_done),
    .ap_continue(Split_U0_ap_continue),
    .ap_idle(Split_U0_ap_idle),
    .ap_ready(Split_U0_ap_ready),
    .start_out(Split_U0_start_out),
    .start_write(Split_U0_start_write),
    .src_rows_V_dout(img_0_rows_V_c20_dout),
    .src_rows_V_empty_n(img_0_rows_V_c20_empty_n),
    .src_rows_V_read(Split_U0_src_rows_V_read),
    .src_cols_V_dout(img_0_cols_V_c21_dout),
    .src_cols_V_empty_n(img_0_cols_V_c21_empty_n),
    .src_cols_V_read(Split_U0_src_cols_V_read),
    .src_data_stream_0_V_dout(img_0_data_stream_0_dout),
    .src_data_stream_0_V_empty_n(img_0_data_stream_0_empty_n),
    .src_data_stream_0_V_read(Split_U0_src_data_stream_0_V_read),
    .src_data_stream_1_V_dout(img_0_data_stream_1_dout),
    .src_data_stream_1_V_empty_n(img_0_data_stream_1_empty_n),
    .src_data_stream_1_V_read(Split_U0_src_data_stream_1_V_read),
    .src_data_stream_2_V_dout(img_0_data_stream_2_dout),
    .src_data_stream_2_V_empty_n(img_0_data_stream_2_empty_n),
    .src_data_stream_2_V_read(Split_U0_src_data_stream_2_V_read),
    .dst0_data_stream_V_din(Split_U0_dst0_data_stream_V_din),
    .dst0_data_stream_V_full_n(img_B_data_stream_0_full_n),
    .dst0_data_stream_V_write(Split_U0_dst0_data_stream_V_write),
    .dst1_data_stream_V_din(Split_U0_dst1_data_stream_V_din),
    .dst1_data_stream_V_full_n(img_G_data_stream_0_full_n),
    .dst1_data_stream_V_write(Split_U0_dst1_data_stream_V_write),
    .dst2_data_stream_V_din(Split_U0_dst2_data_stream_V_din),
    .dst2_data_stream_V_full_n(img_R_data_stream_0_full_n),
    .dst2_data_stream_V_write(Split_U0_dst2_data_stream_V_write)
);

GaussianBlur162 GaussianBlur162_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(GaussianBlur162_U0_ap_start),
    .ap_done(GaussianBlur162_U0_ap_done),
    .ap_continue(GaussianBlur162_U0_ap_continue),
    .ap_idle(GaussianBlur162_U0_ap_idle),
    .ap_ready(GaussianBlur162_U0_ap_ready),
    .p_src_data_stream_V_dout(img_B_data_stream_0_dout),
    .p_src_data_stream_V_empty_n(img_B_data_stream_0_empty_n),
    .p_src_data_stream_V_read(GaussianBlur162_U0_p_src_data_stream_V_read),
    .p_dst_data_stream_V_din(GaussianBlur162_U0_p_dst_data_stream_V_din),
    .p_dst_data_stream_V_full_n(img_B_f_data_stream_s_full_n),
    .p_dst_data_stream_V_write(GaussianBlur162_U0_p_dst_data_stream_V_write)
);

GaussianBlur163 GaussianBlur163_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(GaussianBlur163_U0_ap_start),
    .ap_done(GaussianBlur163_U0_ap_done),
    .ap_continue(GaussianBlur163_U0_ap_continue),
    .ap_idle(GaussianBlur163_U0_ap_idle),
    .ap_ready(GaussianBlur163_U0_ap_ready),
    .p_src_data_stream_V_dout(img_G_data_stream_0_dout),
    .p_src_data_stream_V_empty_n(img_G_data_stream_0_empty_n),
    .p_src_data_stream_V_read(GaussianBlur163_U0_p_src_data_stream_V_read),
    .p_dst_data_stream_V_din(GaussianBlur163_U0_p_dst_data_stream_V_din),
    .p_dst_data_stream_V_full_n(img_G_f_data_stream_s_full_n),
    .p_dst_data_stream_V_write(GaussianBlur163_U0_p_dst_data_stream_V_write)
);

GaussianBlur GaussianBlur_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(GaussianBlur_U0_ap_start),
    .ap_done(GaussianBlur_U0_ap_done),
    .ap_continue(GaussianBlur_U0_ap_continue),
    .ap_idle(GaussianBlur_U0_ap_idle),
    .ap_ready(GaussianBlur_U0_ap_ready),
    .p_src_data_stream_V_dout(img_R_data_stream_0_dout),
    .p_src_data_stream_V_empty_n(img_R_data_stream_0_empty_n),
    .p_src_data_stream_V_read(GaussianBlur_U0_p_src_data_stream_V_read),
    .p_dst_data_stream_V_din(GaussianBlur_U0_p_dst_data_stream_V_din),
    .p_dst_data_stream_V_full_n(img_R_f_data_stream_s_full_n),
    .p_dst_data_stream_V_write(GaussianBlur_U0_p_dst_data_stream_V_write)
);

Merge Merge_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Merge_U0_ap_start),
    .start_full_n(start_for_Mat2AXIvideo_U0_full_n),
    .ap_done(Merge_U0_ap_done),
    .ap_continue(Merge_U0_ap_continue),
    .ap_idle(Merge_U0_ap_idle),
    .ap_ready(Merge_U0_ap_ready),
    .start_out(Merge_U0_start_out),
    .start_write(Merge_U0_start_write),
    .src0_data_stream_V_dout(img_B_f_data_stream_s_dout),
    .src0_data_stream_V_empty_n(img_B_f_data_stream_s_empty_n),
    .src0_data_stream_V_read(Merge_U0_src0_data_stream_V_read),
    .src1_data_stream_V_dout(img_G_f_data_stream_s_dout),
    .src1_data_stream_V_empty_n(img_G_f_data_stream_s_empty_n),
    .src1_data_stream_V_read(Merge_U0_src1_data_stream_V_read),
    .src2_data_stream_V_dout(img_R_f_data_stream_s_dout),
    .src2_data_stream_V_empty_n(img_R_f_data_stream_s_empty_n),
    .src2_data_stream_V_read(Merge_U0_src2_data_stream_V_read),
    .dst_rows_V_dout(img_1_rows_V_c_dout),
    .dst_rows_V_empty_n(img_1_rows_V_c_empty_n),
    .dst_rows_V_read(Merge_U0_dst_rows_V_read),
    .dst_cols_V_dout(img_1_cols_V_c_dout),
    .dst_cols_V_empty_n(img_1_cols_V_c_empty_n),
    .dst_cols_V_read(Merge_U0_dst_cols_V_read),
    .dst_data_stream_0_V_din(Merge_U0_dst_data_stream_0_V_din),
    .dst_data_stream_0_V_full_n(img_1_data_stream_0_full_n),
    .dst_data_stream_0_V_write(Merge_U0_dst_data_stream_0_V_write),
    .dst_data_stream_1_V_din(Merge_U0_dst_data_stream_1_V_din),
    .dst_data_stream_1_V_full_n(img_1_data_stream_1_full_n),
    .dst_data_stream_1_V_write(Merge_U0_dst_data_stream_1_V_write),
    .dst_data_stream_2_V_din(Merge_U0_dst_data_stream_2_V_din),
    .dst_data_stream_2_V_full_n(img_1_data_stream_2_full_n),
    .dst_data_stream_2_V_write(Merge_U0_dst_data_stream_2_V_write),
    .dst_rows_V_out_din(Merge_U0_dst_rows_V_out_din),
    .dst_rows_V_out_full_n(img_1_rows_V_c22_full_n),
    .dst_rows_V_out_write(Merge_U0_dst_rows_V_out_write),
    .dst_cols_V_out_din(Merge_U0_dst_cols_V_out_din),
    .dst_cols_V_out_full_n(img_1_cols_V_c23_full_n),
    .dst_cols_V_out_write(Merge_U0_dst_cols_V_out_write)
);

Mat2AXIvideo Mat2AXIvideo_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Mat2AXIvideo_U0_ap_start),
    .ap_done(Mat2AXIvideo_U0_ap_done),
    .ap_continue(Mat2AXIvideo_U0_ap_continue),
    .ap_idle(Mat2AXIvideo_U0_ap_idle),
    .ap_ready(Mat2AXIvideo_U0_ap_ready),
    .img_rows_V_dout(img_1_rows_V_c22_dout),
    .img_rows_V_empty_n(img_1_rows_V_c22_empty_n),
    .img_rows_V_read(Mat2AXIvideo_U0_img_rows_V_read),
    .img_cols_V_dout(img_1_cols_V_c23_dout),
    .img_cols_V_empty_n(img_1_cols_V_c23_empty_n),
    .img_cols_V_read(Mat2AXIvideo_U0_img_cols_V_read),
    .img_data_stream_0_V_dout(img_1_data_stream_0_dout),
    .img_data_stream_0_V_empty_n(img_1_data_stream_0_empty_n),
    .img_data_stream_0_V_read(Mat2AXIvideo_U0_img_data_stream_0_V_read),
    .img_data_stream_1_V_dout(img_1_data_stream_1_dout),
    .img_data_stream_1_V_empty_n(img_1_data_stream_1_empty_n),
    .img_data_stream_1_V_read(Mat2AXIvideo_U0_img_data_stream_1_V_read),
    .img_data_stream_2_V_dout(img_1_data_stream_2_dout),
    .img_data_stream_2_V_empty_n(img_1_data_stream_2_empty_n),
    .img_data_stream_2_V_read(Mat2AXIvideo_U0_img_data_stream_2_V_read),
    .OUTPUT_STREAM_TDATA(Mat2AXIvideo_U0_OUTPUT_STREAM_TDATA),
    .OUTPUT_STREAM_TVALID(Mat2AXIvideo_U0_OUTPUT_STREAM_TVALID),
    .OUTPUT_STREAM_TREADY(OUTPUT_STREAM_TREADY),
    .OUTPUT_STREAM_TKEEP(Mat2AXIvideo_U0_OUTPUT_STREAM_TKEEP),
    .OUTPUT_STREAM_TSTRB(Mat2AXIvideo_U0_OUTPUT_STREAM_TSTRB),
    .OUTPUT_STREAM_TUSER(Mat2AXIvideo_U0_OUTPUT_STREAM_TUSER),
    .OUTPUT_STREAM_TLAST(Mat2AXIvideo_U0_OUTPUT_STREAM_TLAST),
    .OUTPUT_STREAM_TID(Mat2AXIvideo_U0_OUTPUT_STREAM_TID),
    .OUTPUT_STREAM_TDEST(Mat2AXIvideo_U0_OUTPUT_STREAM_TDEST)
);

fifo_w10_d2_A img_0_rows_V_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_proc_U0_img_0_rows_V_out_din),
    .if_full_n(img_0_rows_V_c_full_n),
    .if_write(Block_proc_U0_img_0_rows_V_out_write),
    .if_dout(img_0_rows_V_c_dout),
    .if_empty_n(img_0_rows_V_c_empty_n),
    .if_read(AXIvideo2Mat_U0_img_rows_V_read)
);

fifo_w11_d2_A img_0_cols_V_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_proc_U0_img_0_cols_V_out_din),
    .if_full_n(img_0_cols_V_c_full_n),
    .if_write(Block_proc_U0_img_0_cols_V_out_write),
    .if_dout(img_0_cols_V_c_dout),
    .if_empty_n(img_0_cols_V_c_empty_n),
    .if_read(AXIvideo2Mat_U0_img_cols_V_read)
);

fifo_w10_d5_A img_1_rows_V_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_proc_U0_img_1_rows_V_out_din),
    .if_full_n(img_1_rows_V_c_full_n),
    .if_write(Block_proc_U0_img_1_rows_V_out_write),
    .if_dout(img_1_rows_V_c_dout),
    .if_empty_n(img_1_rows_V_c_empty_n),
    .if_read(Merge_U0_dst_rows_V_read)
);

fifo_w11_d5_A img_1_cols_V_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_proc_U0_img_1_cols_V_out_din),
    .if_full_n(img_1_cols_V_c_full_n),
    .if_write(Block_proc_U0_img_1_cols_V_out_write),
    .if_dout(img_1_cols_V_c_dout),
    .if_empty_n(img_1_cols_V_c_empty_n),
    .if_read(Merge_U0_dst_cols_V_read)
);

fifo_w8_d2_A img_0_data_stream_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2Mat_U0_img_data_stream_0_V_din),
    .if_full_n(img_0_data_stream_0_full_n),
    .if_write(AXIvideo2Mat_U0_img_data_stream_0_V_write),
    .if_dout(img_0_data_stream_0_dout),
    .if_empty_n(img_0_data_stream_0_empty_n),
    .if_read(Split_U0_src_data_stream_0_V_read)
);

fifo_w8_d2_A img_0_data_stream_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2Mat_U0_img_data_stream_1_V_din),
    .if_full_n(img_0_data_stream_1_full_n),
    .if_write(AXIvideo2Mat_U0_img_data_stream_1_V_write),
    .if_dout(img_0_data_stream_1_dout),
    .if_empty_n(img_0_data_stream_1_empty_n),
    .if_read(Split_U0_src_data_stream_1_V_read)
);

fifo_w8_d2_A img_0_data_stream_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2Mat_U0_img_data_stream_2_V_din),
    .if_full_n(img_0_data_stream_2_full_n),
    .if_write(AXIvideo2Mat_U0_img_data_stream_2_V_write),
    .if_dout(img_0_data_stream_2_dout),
    .if_empty_n(img_0_data_stream_2_empty_n),
    .if_read(Split_U0_src_data_stream_2_V_read)
);

fifo_w10_d2_A img_0_rows_V_c20_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2Mat_U0_img_rows_V_out_din),
    .if_full_n(img_0_rows_V_c20_full_n),
    .if_write(AXIvideo2Mat_U0_img_rows_V_out_write),
    .if_dout(img_0_rows_V_c20_dout),
    .if_empty_n(img_0_rows_V_c20_empty_n),
    .if_read(Split_U0_src_rows_V_read)
);

fifo_w11_d2_A img_0_cols_V_c21_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2Mat_U0_img_cols_V_out_din),
    .if_full_n(img_0_cols_V_c21_full_n),
    .if_write(AXIvideo2Mat_U0_img_cols_V_out_write),
    .if_dout(img_0_cols_V_c21_dout),
    .if_empty_n(img_0_cols_V_c21_empty_n),
    .if_read(Split_U0_src_cols_V_read)
);

fifo_w8_d2_A img_B_data_stream_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Split_U0_dst0_data_stream_V_din),
    .if_full_n(img_B_data_stream_0_full_n),
    .if_write(Split_U0_dst0_data_stream_V_write),
    .if_dout(img_B_data_stream_0_dout),
    .if_empty_n(img_B_data_stream_0_empty_n),
    .if_read(GaussianBlur162_U0_p_src_data_stream_V_read)
);

fifo_w8_d2_A img_G_data_stream_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Split_U0_dst1_data_stream_V_din),
    .if_full_n(img_G_data_stream_0_full_n),
    .if_write(Split_U0_dst1_data_stream_V_write),
    .if_dout(img_G_data_stream_0_dout),
    .if_empty_n(img_G_data_stream_0_empty_n),
    .if_read(GaussianBlur163_U0_p_src_data_stream_V_read)
);

fifo_w8_d2_A img_R_data_stream_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Split_U0_dst2_data_stream_V_din),
    .if_full_n(img_R_data_stream_0_full_n),
    .if_write(Split_U0_dst2_data_stream_V_write),
    .if_dout(img_R_data_stream_0_dout),
    .if_empty_n(img_R_data_stream_0_empty_n),
    .if_read(GaussianBlur_U0_p_src_data_stream_V_read)
);

fifo_w8_d2_A img_B_f_data_stream_s_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(GaussianBlur162_U0_p_dst_data_stream_V_din),
    .if_full_n(img_B_f_data_stream_s_full_n),
    .if_write(GaussianBlur162_U0_p_dst_data_stream_V_write),
    .if_dout(img_B_f_data_stream_s_dout),
    .if_empty_n(img_B_f_data_stream_s_empty_n),
    .if_read(Merge_U0_src0_data_stream_V_read)
);

fifo_w8_d2_A img_G_f_data_stream_s_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(GaussianBlur163_U0_p_dst_data_stream_V_din),
    .if_full_n(img_G_f_data_stream_s_full_n),
    .if_write(GaussianBlur163_U0_p_dst_data_stream_V_write),
    .if_dout(img_G_f_data_stream_s_dout),
    .if_empty_n(img_G_f_data_stream_s_empty_n),
    .if_read(Merge_U0_src1_data_stream_V_read)
);

fifo_w8_d2_A img_R_f_data_stream_s_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(GaussianBlur_U0_p_dst_data_stream_V_din),
    .if_full_n(img_R_f_data_stream_s_full_n),
    .if_write(GaussianBlur_U0_p_dst_data_stream_V_write),
    .if_dout(img_R_f_data_stream_s_dout),
    .if_empty_n(img_R_f_data_stream_s_empty_n),
    .if_read(Merge_U0_src2_data_stream_V_read)
);

fifo_w8_d2_A img_1_data_stream_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Merge_U0_dst_data_stream_0_V_din),
    .if_full_n(img_1_data_stream_0_full_n),
    .if_write(Merge_U0_dst_data_stream_0_V_write),
    .if_dout(img_1_data_stream_0_dout),
    .if_empty_n(img_1_data_stream_0_empty_n),
    .if_read(Mat2AXIvideo_U0_img_data_stream_0_V_read)
);

fifo_w8_d2_A img_1_data_stream_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Merge_U0_dst_data_stream_1_V_din),
    .if_full_n(img_1_data_stream_1_full_n),
    .if_write(Merge_U0_dst_data_stream_1_V_write),
    .if_dout(img_1_data_stream_1_dout),
    .if_empty_n(img_1_data_stream_1_empty_n),
    .if_read(Mat2AXIvideo_U0_img_data_stream_1_V_read)
);

fifo_w8_d2_A img_1_data_stream_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Merge_U0_dst_data_stream_2_V_din),
    .if_full_n(img_1_data_stream_2_full_n),
    .if_write(Merge_U0_dst_data_stream_2_V_write),
    .if_dout(img_1_data_stream_2_dout),
    .if_empty_n(img_1_data_stream_2_empty_n),
    .if_read(Mat2AXIvideo_U0_img_data_stream_2_V_read)
);

fifo_w10_d2_A img_1_rows_V_c22_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Merge_U0_dst_rows_V_out_din),
    .if_full_n(img_1_rows_V_c22_full_n),
    .if_write(Merge_U0_dst_rows_V_out_write),
    .if_dout(img_1_rows_V_c22_dout),
    .if_empty_n(img_1_rows_V_c22_empty_n),
    .if_read(Mat2AXIvideo_U0_img_rows_V_read)
);

fifo_w11_d2_A img_1_cols_V_c23_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Merge_U0_dst_cols_V_out_din),
    .if_full_n(img_1_cols_V_c23_full_n),
    .if_write(Merge_U0_dst_cols_V_out_write),
    .if_dout(img_1_cols_V_c23_dout),
    .if_empty_n(img_1_cols_V_c23_empty_n),
    .if_read(Mat2AXIvideo_U0_img_cols_V_read)
);

start_for_Merge_U0 start_for_Merge_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Merge_U0_din),
    .if_full_n(start_for_Merge_U0_full_n),
    .if_write(Block_proc_U0_start_write),
    .if_dout(start_for_Merge_U0_dout),
    .if_empty_n(start_for_Merge_U0_empty_n),
    .if_read(Merge_U0_ap_ready)
);

start_for_Split_U0 start_for_Split_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Split_U0_din),
    .if_full_n(start_for_Split_U0_full_n),
    .if_write(AXIvideo2Mat_U0_start_write),
    .if_dout(start_for_Split_U0_dout),
    .if_empty_n(start_for_Split_U0_empty_n),
    .if_read(Split_U0_ap_ready)
);

start_for_GaussiajbC start_for_GaussiajbC_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_GaussianBlur162_U0_din),
    .if_full_n(start_for_GaussianBlur162_U0_full_n),
    .if_write(Split_U0_start_write),
    .if_dout(start_for_GaussianBlur162_U0_dout),
    .if_empty_n(start_for_GaussianBlur162_U0_empty_n),
    .if_read(GaussianBlur162_U0_ap_ready)
);

start_for_GaussiakbM start_for_GaussiakbM_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_GaussianBlur163_U0_din),
    .if_full_n(start_for_GaussianBlur163_U0_full_n),
    .if_write(Split_U0_start_write),
    .if_dout(start_for_GaussianBlur163_U0_dout),
    .if_empty_n(start_for_GaussianBlur163_U0_empty_n),
    .if_read(GaussianBlur163_U0_ap_ready)
);

start_for_GaussialbW start_for_GaussialbW_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_GaussianBlur_U0_din),
    .if_full_n(start_for_GaussianBlur_U0_full_n),
    .if_write(Split_U0_start_write),
    .if_dout(start_for_GaussianBlur_U0_dout),
    .if_empty_n(start_for_GaussianBlur_U0_empty_n),
    .if_read(GaussianBlur_U0_ap_ready)
);

start_for_Mat2AXImb6 start_for_Mat2AXImb6_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Mat2AXIvideo_U0_din),
    .if_full_n(start_for_Mat2AXIvideo_U0_full_n),
    .if_write(Merge_U0_start_write),
    .if_dout(start_for_Mat2AXIvideo_U0_dout),
    .if_empty_n(start_for_Mat2AXIvideo_U0_empty_n),
    .if_read(Mat2AXIvideo_U0_ap_ready)
);

assign AXIvideo2Mat_U0_ap_continue = 1'b1;

assign AXIvideo2Mat_U0_ap_start = 1'b1;

assign Block_proc_U0_ap_continue = 1'b1;

assign Block_proc_U0_ap_start = 1'b1;

assign GaussianBlur162_U0_ap_continue = 1'b1;

assign GaussianBlur162_U0_ap_start = start_for_GaussianBlur162_U0_empty_n;

assign GaussianBlur162_U0_start_full_n = 1'b1;

assign GaussianBlur162_U0_start_write = 1'b0;

assign GaussianBlur163_U0_ap_continue = 1'b1;

assign GaussianBlur163_U0_ap_start = start_for_GaussianBlur163_U0_empty_n;

assign GaussianBlur163_U0_start_full_n = 1'b1;

assign GaussianBlur163_U0_start_write = 1'b0;

assign GaussianBlur_U0_ap_continue = 1'b1;

assign GaussianBlur_U0_ap_start = start_for_GaussianBlur_U0_empty_n;

assign GaussianBlur_U0_start_full_n = 1'b1;

assign GaussianBlur_U0_start_write = 1'b0;

assign INPUT_STREAM_TREADY = AXIvideo2Mat_U0_INPUT_STREAM_TREADY;

assign Mat2AXIvideo_U0_ap_continue = 1'b1;

assign Mat2AXIvideo_U0_ap_start = start_for_Mat2AXIvideo_U0_empty_n;

assign Mat2AXIvideo_U0_start_full_n = 1'b1;

assign Mat2AXIvideo_U0_start_write = 1'b0;

assign Merge_U0_ap_continue = 1'b1;

assign Merge_U0_ap_start = start_for_Merge_U0_empty_n;

assign OUTPUT_STREAM_TDATA = Mat2AXIvideo_U0_OUTPUT_STREAM_TDATA;

assign OUTPUT_STREAM_TDEST = Mat2AXIvideo_U0_OUTPUT_STREAM_TDEST;

assign OUTPUT_STREAM_TID = Mat2AXIvideo_U0_OUTPUT_STREAM_TID;

assign OUTPUT_STREAM_TKEEP = Mat2AXIvideo_U0_OUTPUT_STREAM_TKEEP;

assign OUTPUT_STREAM_TLAST = Mat2AXIvideo_U0_OUTPUT_STREAM_TLAST;

assign OUTPUT_STREAM_TSTRB = Mat2AXIvideo_U0_OUTPUT_STREAM_TSTRB;

assign OUTPUT_STREAM_TUSER = Mat2AXIvideo_U0_OUTPUT_STREAM_TUSER;

assign OUTPUT_STREAM_TVALID = Mat2AXIvideo_U0_OUTPUT_STREAM_TVALID;

assign Split_U0_ap_continue = 1'b1;

assign Split_U0_ap_start = start_for_Split_U0_empty_n;

assign Split_U0_start_full_n = (start_for_GaussianBlur_U0_full_n & start_for_GaussianBlur163_U0_full_n & start_for_GaussianBlur162_U0_full_n);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_continue = 1'b0;

assign start_for_GaussianBlur162_U0_din = 1'b1;

assign start_for_GaussianBlur163_U0_din = 1'b1;

assign start_for_GaussianBlur_U0_din = 1'b1;

assign start_for_Mat2AXIvideo_U0_din = 1'b1;

assign start_for_Merge_U0_din = 1'b1;

assign start_for_Split_U0_din = 1'b1;

endmodule //ov5640_GaussianBlur
