// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "ov5640_GaussianBlur.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_lv<24> ov5640_GaussianBlur::ap_const_lv24_0 = "000000000000000000000000";
const sc_lv<3> ov5640_GaussianBlur::ap_const_lv3_0 = "000";
const sc_lv<1> ov5640_GaussianBlur::ap_const_lv1_0 = "0";
const sc_logic ov5640_GaussianBlur::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic ov5640_GaussianBlur::ap_const_logic_0 = sc_dt::Log_0;

ov5640_GaussianBlur::ov5640_GaussianBlur(sc_module_name name) : sc_module(name), mVcdFile(0) {
    Block_proc_U0 = new Block_proc("Block_proc_U0");
    Block_proc_U0->ap_clk(ap_clk);
    Block_proc_U0->ap_rst(ap_rst_n_inv);
    Block_proc_U0->ap_start(Block_proc_U0_ap_start);
    Block_proc_U0->start_full_n(start_for_Merge_U0_full_n);
    Block_proc_U0->ap_done(Block_proc_U0_ap_done);
    Block_proc_U0->ap_continue(Block_proc_U0_ap_continue);
    Block_proc_U0->ap_idle(Block_proc_U0_ap_idle);
    Block_proc_U0->ap_ready(Block_proc_U0_ap_ready);
    Block_proc_U0->start_out(Block_proc_U0_start_out);
    Block_proc_U0->start_write(Block_proc_U0_start_write);
    Block_proc_U0->img_0_rows_V_out_din(Block_proc_U0_img_0_rows_V_out_din);
    Block_proc_U0->img_0_rows_V_out_full_n(img_0_rows_V_c_full_n);
    Block_proc_U0->img_0_rows_V_out_write(Block_proc_U0_img_0_rows_V_out_write);
    Block_proc_U0->img_0_cols_V_out_din(Block_proc_U0_img_0_cols_V_out_din);
    Block_proc_U0->img_0_cols_V_out_full_n(img_0_cols_V_c_full_n);
    Block_proc_U0->img_0_cols_V_out_write(Block_proc_U0_img_0_cols_V_out_write);
    Block_proc_U0->img_1_rows_V_out_din(Block_proc_U0_img_1_rows_V_out_din);
    Block_proc_U0->img_1_rows_V_out_full_n(img_1_rows_V_c_full_n);
    Block_proc_U0->img_1_rows_V_out_write(Block_proc_U0_img_1_rows_V_out_write);
    Block_proc_U0->img_1_cols_V_out_din(Block_proc_U0_img_1_cols_V_out_din);
    Block_proc_U0->img_1_cols_V_out_full_n(img_1_cols_V_c_full_n);
    Block_proc_U0->img_1_cols_V_out_write(Block_proc_U0_img_1_cols_V_out_write);
    AXIvideo2Mat_U0 = new AXIvideo2Mat("AXIvideo2Mat_U0");
    AXIvideo2Mat_U0->ap_clk(ap_clk);
    AXIvideo2Mat_U0->ap_rst(ap_rst_n_inv);
    AXIvideo2Mat_U0->ap_start(AXIvideo2Mat_U0_ap_start);
    AXIvideo2Mat_U0->start_full_n(start_for_Split_U0_full_n);
    AXIvideo2Mat_U0->ap_done(AXIvideo2Mat_U0_ap_done);
    AXIvideo2Mat_U0->ap_continue(AXIvideo2Mat_U0_ap_continue);
    AXIvideo2Mat_U0->ap_idle(AXIvideo2Mat_U0_ap_idle);
    AXIvideo2Mat_U0->ap_ready(AXIvideo2Mat_U0_ap_ready);
    AXIvideo2Mat_U0->start_out(AXIvideo2Mat_U0_start_out);
    AXIvideo2Mat_U0->start_write(AXIvideo2Mat_U0_start_write);
    AXIvideo2Mat_U0->INPUT_STREAM_TDATA(INPUT_STREAM_TDATA);
    AXIvideo2Mat_U0->INPUT_STREAM_TVALID(INPUT_STREAM_TVALID);
    AXIvideo2Mat_U0->INPUT_STREAM_TREADY(AXIvideo2Mat_U0_INPUT_STREAM_TREADY);
    AXIvideo2Mat_U0->INPUT_STREAM_TKEEP(INPUT_STREAM_TKEEP);
    AXIvideo2Mat_U0->INPUT_STREAM_TSTRB(INPUT_STREAM_TSTRB);
    AXIvideo2Mat_U0->INPUT_STREAM_TUSER(INPUT_STREAM_TUSER);
    AXIvideo2Mat_U0->INPUT_STREAM_TLAST(INPUT_STREAM_TLAST);
    AXIvideo2Mat_U0->INPUT_STREAM_TID(INPUT_STREAM_TID);
    AXIvideo2Mat_U0->INPUT_STREAM_TDEST(INPUT_STREAM_TDEST);
    AXIvideo2Mat_U0->img_rows_V_dout(img_0_rows_V_c_dout);
    AXIvideo2Mat_U0->img_rows_V_empty_n(img_0_rows_V_c_empty_n);
    AXIvideo2Mat_U0->img_rows_V_read(AXIvideo2Mat_U0_img_rows_V_read);
    AXIvideo2Mat_U0->img_cols_V_dout(img_0_cols_V_c_dout);
    AXIvideo2Mat_U0->img_cols_V_empty_n(img_0_cols_V_c_empty_n);
    AXIvideo2Mat_U0->img_cols_V_read(AXIvideo2Mat_U0_img_cols_V_read);
    AXIvideo2Mat_U0->img_data_stream_0_V_din(AXIvideo2Mat_U0_img_data_stream_0_V_din);
    AXIvideo2Mat_U0->img_data_stream_0_V_full_n(img_0_data_stream_0_full_n);
    AXIvideo2Mat_U0->img_data_stream_0_V_write(AXIvideo2Mat_U0_img_data_stream_0_V_write);
    AXIvideo2Mat_U0->img_data_stream_1_V_din(AXIvideo2Mat_U0_img_data_stream_1_V_din);
    AXIvideo2Mat_U0->img_data_stream_1_V_full_n(img_0_data_stream_1_full_n);
    AXIvideo2Mat_U0->img_data_stream_1_V_write(AXIvideo2Mat_U0_img_data_stream_1_V_write);
    AXIvideo2Mat_U0->img_data_stream_2_V_din(AXIvideo2Mat_U0_img_data_stream_2_V_din);
    AXIvideo2Mat_U0->img_data_stream_2_V_full_n(img_0_data_stream_2_full_n);
    AXIvideo2Mat_U0->img_data_stream_2_V_write(AXIvideo2Mat_U0_img_data_stream_2_V_write);
    AXIvideo2Mat_U0->img_rows_V_out_din(AXIvideo2Mat_U0_img_rows_V_out_din);
    AXIvideo2Mat_U0->img_rows_V_out_full_n(img_0_rows_V_c20_full_n);
    AXIvideo2Mat_U0->img_rows_V_out_write(AXIvideo2Mat_U0_img_rows_V_out_write);
    AXIvideo2Mat_U0->img_cols_V_out_din(AXIvideo2Mat_U0_img_cols_V_out_din);
    AXIvideo2Mat_U0->img_cols_V_out_full_n(img_0_cols_V_c21_full_n);
    AXIvideo2Mat_U0->img_cols_V_out_write(AXIvideo2Mat_U0_img_cols_V_out_write);
    Split_U0 = new Split("Split_U0");
    Split_U0->ap_clk(ap_clk);
    Split_U0->ap_rst(ap_rst_n_inv);
    Split_U0->ap_start(Split_U0_ap_start);
    Split_U0->start_full_n(Split_U0_start_full_n);
    Split_U0->ap_done(Split_U0_ap_done);
    Split_U0->ap_continue(Split_U0_ap_continue);
    Split_U0->ap_idle(Split_U0_ap_idle);
    Split_U0->ap_ready(Split_U0_ap_ready);
    Split_U0->start_out(Split_U0_start_out);
    Split_U0->start_write(Split_U0_start_write);
    Split_U0->src_rows_V_dout(img_0_rows_V_c20_dout);
    Split_U0->src_rows_V_empty_n(img_0_rows_V_c20_empty_n);
    Split_U0->src_rows_V_read(Split_U0_src_rows_V_read);
    Split_U0->src_cols_V_dout(img_0_cols_V_c21_dout);
    Split_U0->src_cols_V_empty_n(img_0_cols_V_c21_empty_n);
    Split_U0->src_cols_V_read(Split_U0_src_cols_V_read);
    Split_U0->src_data_stream_0_V_dout(img_0_data_stream_0_dout);
    Split_U0->src_data_stream_0_V_empty_n(img_0_data_stream_0_empty_n);
    Split_U0->src_data_stream_0_V_read(Split_U0_src_data_stream_0_V_read);
    Split_U0->src_data_stream_1_V_dout(img_0_data_stream_1_dout);
    Split_U0->src_data_stream_1_V_empty_n(img_0_data_stream_1_empty_n);
    Split_U0->src_data_stream_1_V_read(Split_U0_src_data_stream_1_V_read);
    Split_U0->src_data_stream_2_V_dout(img_0_data_stream_2_dout);
    Split_U0->src_data_stream_2_V_empty_n(img_0_data_stream_2_empty_n);
    Split_U0->src_data_stream_2_V_read(Split_U0_src_data_stream_2_V_read);
    Split_U0->dst0_data_stream_V_din(Split_U0_dst0_data_stream_V_din);
    Split_U0->dst0_data_stream_V_full_n(img_B_data_stream_0_full_n);
    Split_U0->dst0_data_stream_V_write(Split_U0_dst0_data_stream_V_write);
    Split_U0->dst1_data_stream_V_din(Split_U0_dst1_data_stream_V_din);
    Split_U0->dst1_data_stream_V_full_n(img_G_data_stream_0_full_n);
    Split_U0->dst1_data_stream_V_write(Split_U0_dst1_data_stream_V_write);
    Split_U0->dst2_data_stream_V_din(Split_U0_dst2_data_stream_V_din);
    Split_U0->dst2_data_stream_V_full_n(img_R_data_stream_0_full_n);
    Split_U0->dst2_data_stream_V_write(Split_U0_dst2_data_stream_V_write);
    GaussianBlur162_U0 = new GaussianBlur162("GaussianBlur162_U0");
    GaussianBlur162_U0->ap_clk(ap_clk);
    GaussianBlur162_U0->ap_rst(ap_rst_n_inv);
    GaussianBlur162_U0->ap_start(GaussianBlur162_U0_ap_start);
    GaussianBlur162_U0->ap_done(GaussianBlur162_U0_ap_done);
    GaussianBlur162_U0->ap_continue(GaussianBlur162_U0_ap_continue);
    GaussianBlur162_U0->ap_idle(GaussianBlur162_U0_ap_idle);
    GaussianBlur162_U0->ap_ready(GaussianBlur162_U0_ap_ready);
    GaussianBlur162_U0->p_src_data_stream_V_dout(img_B_data_stream_0_dout);
    GaussianBlur162_U0->p_src_data_stream_V_empty_n(img_B_data_stream_0_empty_n);
    GaussianBlur162_U0->p_src_data_stream_V_read(GaussianBlur162_U0_p_src_data_stream_V_read);
    GaussianBlur162_U0->p_dst_data_stream_V_din(GaussianBlur162_U0_p_dst_data_stream_V_din);
    GaussianBlur162_U0->p_dst_data_stream_V_full_n(img_B_f_data_stream_s_full_n);
    GaussianBlur162_U0->p_dst_data_stream_V_write(GaussianBlur162_U0_p_dst_data_stream_V_write);
    GaussianBlur163_U0 = new GaussianBlur163("GaussianBlur163_U0");
    GaussianBlur163_U0->ap_clk(ap_clk);
    GaussianBlur163_U0->ap_rst(ap_rst_n_inv);
    GaussianBlur163_U0->ap_start(GaussianBlur163_U0_ap_start);
    GaussianBlur163_U0->ap_done(GaussianBlur163_U0_ap_done);
    GaussianBlur163_U0->ap_continue(GaussianBlur163_U0_ap_continue);
    GaussianBlur163_U0->ap_idle(GaussianBlur163_U0_ap_idle);
    GaussianBlur163_U0->ap_ready(GaussianBlur163_U0_ap_ready);
    GaussianBlur163_U0->p_src_data_stream_V_dout(img_G_data_stream_0_dout);
    GaussianBlur163_U0->p_src_data_stream_V_empty_n(img_G_data_stream_0_empty_n);
    GaussianBlur163_U0->p_src_data_stream_V_read(GaussianBlur163_U0_p_src_data_stream_V_read);
    GaussianBlur163_U0->p_dst_data_stream_V_din(GaussianBlur163_U0_p_dst_data_stream_V_din);
    GaussianBlur163_U0->p_dst_data_stream_V_full_n(img_G_f_data_stream_s_full_n);
    GaussianBlur163_U0->p_dst_data_stream_V_write(GaussianBlur163_U0_p_dst_data_stream_V_write);
    GaussianBlur_U0 = new GaussianBlur("GaussianBlur_U0");
    GaussianBlur_U0->ap_clk(ap_clk);
    GaussianBlur_U0->ap_rst(ap_rst_n_inv);
    GaussianBlur_U0->ap_start(GaussianBlur_U0_ap_start);
    GaussianBlur_U0->ap_done(GaussianBlur_U0_ap_done);
    GaussianBlur_U0->ap_continue(GaussianBlur_U0_ap_continue);
    GaussianBlur_U0->ap_idle(GaussianBlur_U0_ap_idle);
    GaussianBlur_U0->ap_ready(GaussianBlur_U0_ap_ready);
    GaussianBlur_U0->p_src_data_stream_V_dout(img_R_data_stream_0_dout);
    GaussianBlur_U0->p_src_data_stream_V_empty_n(img_R_data_stream_0_empty_n);
    GaussianBlur_U0->p_src_data_stream_V_read(GaussianBlur_U0_p_src_data_stream_V_read);
    GaussianBlur_U0->p_dst_data_stream_V_din(GaussianBlur_U0_p_dst_data_stream_V_din);
    GaussianBlur_U0->p_dst_data_stream_V_full_n(img_R_f_data_stream_s_full_n);
    GaussianBlur_U0->p_dst_data_stream_V_write(GaussianBlur_U0_p_dst_data_stream_V_write);
    Merge_U0 = new Merge("Merge_U0");
    Merge_U0->ap_clk(ap_clk);
    Merge_U0->ap_rst(ap_rst_n_inv);
    Merge_U0->ap_start(Merge_U0_ap_start);
    Merge_U0->start_full_n(start_for_Mat2AXIvideo_U0_full_n);
    Merge_U0->ap_done(Merge_U0_ap_done);
    Merge_U0->ap_continue(Merge_U0_ap_continue);
    Merge_U0->ap_idle(Merge_U0_ap_idle);
    Merge_U0->ap_ready(Merge_U0_ap_ready);
    Merge_U0->start_out(Merge_U0_start_out);
    Merge_U0->start_write(Merge_U0_start_write);
    Merge_U0->src0_data_stream_V_dout(img_B_f_data_stream_s_dout);
    Merge_U0->src0_data_stream_V_empty_n(img_B_f_data_stream_s_empty_n);
    Merge_U0->src0_data_stream_V_read(Merge_U0_src0_data_stream_V_read);
    Merge_U0->src1_data_stream_V_dout(img_G_f_data_stream_s_dout);
    Merge_U0->src1_data_stream_V_empty_n(img_G_f_data_stream_s_empty_n);
    Merge_U0->src1_data_stream_V_read(Merge_U0_src1_data_stream_V_read);
    Merge_U0->src2_data_stream_V_dout(img_R_f_data_stream_s_dout);
    Merge_U0->src2_data_stream_V_empty_n(img_R_f_data_stream_s_empty_n);
    Merge_U0->src2_data_stream_V_read(Merge_U0_src2_data_stream_V_read);
    Merge_U0->dst_rows_V_dout(img_1_rows_V_c_dout);
    Merge_U0->dst_rows_V_empty_n(img_1_rows_V_c_empty_n);
    Merge_U0->dst_rows_V_read(Merge_U0_dst_rows_V_read);
    Merge_U0->dst_cols_V_dout(img_1_cols_V_c_dout);
    Merge_U0->dst_cols_V_empty_n(img_1_cols_V_c_empty_n);
    Merge_U0->dst_cols_V_read(Merge_U0_dst_cols_V_read);
    Merge_U0->dst_data_stream_0_V_din(Merge_U0_dst_data_stream_0_V_din);
    Merge_U0->dst_data_stream_0_V_full_n(img_1_data_stream_0_full_n);
    Merge_U0->dst_data_stream_0_V_write(Merge_U0_dst_data_stream_0_V_write);
    Merge_U0->dst_data_stream_1_V_din(Merge_U0_dst_data_stream_1_V_din);
    Merge_U0->dst_data_stream_1_V_full_n(img_1_data_stream_1_full_n);
    Merge_U0->dst_data_stream_1_V_write(Merge_U0_dst_data_stream_1_V_write);
    Merge_U0->dst_data_stream_2_V_din(Merge_U0_dst_data_stream_2_V_din);
    Merge_U0->dst_data_stream_2_V_full_n(img_1_data_stream_2_full_n);
    Merge_U0->dst_data_stream_2_V_write(Merge_U0_dst_data_stream_2_V_write);
    Merge_U0->dst_rows_V_out_din(Merge_U0_dst_rows_V_out_din);
    Merge_U0->dst_rows_V_out_full_n(img_1_rows_V_c22_full_n);
    Merge_U0->dst_rows_V_out_write(Merge_U0_dst_rows_V_out_write);
    Merge_U0->dst_cols_V_out_din(Merge_U0_dst_cols_V_out_din);
    Merge_U0->dst_cols_V_out_full_n(img_1_cols_V_c23_full_n);
    Merge_U0->dst_cols_V_out_write(Merge_U0_dst_cols_V_out_write);
    Mat2AXIvideo_U0 = new Mat2AXIvideo("Mat2AXIvideo_U0");
    Mat2AXIvideo_U0->ap_clk(ap_clk);
    Mat2AXIvideo_U0->ap_rst(ap_rst_n_inv);
    Mat2AXIvideo_U0->ap_start(Mat2AXIvideo_U0_ap_start);
    Mat2AXIvideo_U0->ap_done(Mat2AXIvideo_U0_ap_done);
    Mat2AXIvideo_U0->ap_continue(Mat2AXIvideo_U0_ap_continue);
    Mat2AXIvideo_U0->ap_idle(Mat2AXIvideo_U0_ap_idle);
    Mat2AXIvideo_U0->ap_ready(Mat2AXIvideo_U0_ap_ready);
    Mat2AXIvideo_U0->img_rows_V_dout(img_1_rows_V_c22_dout);
    Mat2AXIvideo_U0->img_rows_V_empty_n(img_1_rows_V_c22_empty_n);
    Mat2AXIvideo_U0->img_rows_V_read(Mat2AXIvideo_U0_img_rows_V_read);
    Mat2AXIvideo_U0->img_cols_V_dout(img_1_cols_V_c23_dout);
    Mat2AXIvideo_U0->img_cols_V_empty_n(img_1_cols_V_c23_empty_n);
    Mat2AXIvideo_U0->img_cols_V_read(Mat2AXIvideo_U0_img_cols_V_read);
    Mat2AXIvideo_U0->img_data_stream_0_V_dout(img_1_data_stream_0_dout);
    Mat2AXIvideo_U0->img_data_stream_0_V_empty_n(img_1_data_stream_0_empty_n);
    Mat2AXIvideo_U0->img_data_stream_0_V_read(Mat2AXIvideo_U0_img_data_stream_0_V_read);
    Mat2AXIvideo_U0->img_data_stream_1_V_dout(img_1_data_stream_1_dout);
    Mat2AXIvideo_U0->img_data_stream_1_V_empty_n(img_1_data_stream_1_empty_n);
    Mat2AXIvideo_U0->img_data_stream_1_V_read(Mat2AXIvideo_U0_img_data_stream_1_V_read);
    Mat2AXIvideo_U0->img_data_stream_2_V_dout(img_1_data_stream_2_dout);
    Mat2AXIvideo_U0->img_data_stream_2_V_empty_n(img_1_data_stream_2_empty_n);
    Mat2AXIvideo_U0->img_data_stream_2_V_read(Mat2AXIvideo_U0_img_data_stream_2_V_read);
    Mat2AXIvideo_U0->OUTPUT_STREAM_TDATA(Mat2AXIvideo_U0_OUTPUT_STREAM_TDATA);
    Mat2AXIvideo_U0->OUTPUT_STREAM_TVALID(Mat2AXIvideo_U0_OUTPUT_STREAM_TVALID);
    Mat2AXIvideo_U0->OUTPUT_STREAM_TREADY(OUTPUT_STREAM_TREADY);
    Mat2AXIvideo_U0->OUTPUT_STREAM_TKEEP(Mat2AXIvideo_U0_OUTPUT_STREAM_TKEEP);
    Mat2AXIvideo_U0->OUTPUT_STREAM_TSTRB(Mat2AXIvideo_U0_OUTPUT_STREAM_TSTRB);
    Mat2AXIvideo_U0->OUTPUT_STREAM_TUSER(Mat2AXIvideo_U0_OUTPUT_STREAM_TUSER);
    Mat2AXIvideo_U0->OUTPUT_STREAM_TLAST(Mat2AXIvideo_U0_OUTPUT_STREAM_TLAST);
    Mat2AXIvideo_U0->OUTPUT_STREAM_TID(Mat2AXIvideo_U0_OUTPUT_STREAM_TID);
    Mat2AXIvideo_U0->OUTPUT_STREAM_TDEST(Mat2AXIvideo_U0_OUTPUT_STREAM_TDEST);
    img_0_rows_V_c_U = new fifo_w10_d2_A("img_0_rows_V_c_U");
    img_0_rows_V_c_U->clk(ap_clk);
    img_0_rows_V_c_U->reset(ap_rst_n_inv);
    img_0_rows_V_c_U->if_read_ce(ap_var_for_const0);
    img_0_rows_V_c_U->if_write_ce(ap_var_for_const0);
    img_0_rows_V_c_U->if_din(Block_proc_U0_img_0_rows_V_out_din);
    img_0_rows_V_c_U->if_full_n(img_0_rows_V_c_full_n);
    img_0_rows_V_c_U->if_write(Block_proc_U0_img_0_rows_V_out_write);
    img_0_rows_V_c_U->if_dout(img_0_rows_V_c_dout);
    img_0_rows_V_c_U->if_empty_n(img_0_rows_V_c_empty_n);
    img_0_rows_V_c_U->if_read(AXIvideo2Mat_U0_img_rows_V_read);
    img_0_cols_V_c_U = new fifo_w11_d2_A("img_0_cols_V_c_U");
    img_0_cols_V_c_U->clk(ap_clk);
    img_0_cols_V_c_U->reset(ap_rst_n_inv);
    img_0_cols_V_c_U->if_read_ce(ap_var_for_const0);
    img_0_cols_V_c_U->if_write_ce(ap_var_for_const0);
    img_0_cols_V_c_U->if_din(Block_proc_U0_img_0_cols_V_out_din);
    img_0_cols_V_c_U->if_full_n(img_0_cols_V_c_full_n);
    img_0_cols_V_c_U->if_write(Block_proc_U0_img_0_cols_V_out_write);
    img_0_cols_V_c_U->if_dout(img_0_cols_V_c_dout);
    img_0_cols_V_c_U->if_empty_n(img_0_cols_V_c_empty_n);
    img_0_cols_V_c_U->if_read(AXIvideo2Mat_U0_img_cols_V_read);
    img_1_rows_V_c_U = new fifo_w10_d5_A("img_1_rows_V_c_U");
    img_1_rows_V_c_U->clk(ap_clk);
    img_1_rows_V_c_U->reset(ap_rst_n_inv);
    img_1_rows_V_c_U->if_read_ce(ap_var_for_const0);
    img_1_rows_V_c_U->if_write_ce(ap_var_for_const0);
    img_1_rows_V_c_U->if_din(Block_proc_U0_img_1_rows_V_out_din);
    img_1_rows_V_c_U->if_full_n(img_1_rows_V_c_full_n);
    img_1_rows_V_c_U->if_write(Block_proc_U0_img_1_rows_V_out_write);
    img_1_rows_V_c_U->if_dout(img_1_rows_V_c_dout);
    img_1_rows_V_c_U->if_empty_n(img_1_rows_V_c_empty_n);
    img_1_rows_V_c_U->if_read(Merge_U0_dst_rows_V_read);
    img_1_cols_V_c_U = new fifo_w11_d5_A("img_1_cols_V_c_U");
    img_1_cols_V_c_U->clk(ap_clk);
    img_1_cols_V_c_U->reset(ap_rst_n_inv);
    img_1_cols_V_c_U->if_read_ce(ap_var_for_const0);
    img_1_cols_V_c_U->if_write_ce(ap_var_for_const0);
    img_1_cols_V_c_U->if_din(Block_proc_U0_img_1_cols_V_out_din);
    img_1_cols_V_c_U->if_full_n(img_1_cols_V_c_full_n);
    img_1_cols_V_c_U->if_write(Block_proc_U0_img_1_cols_V_out_write);
    img_1_cols_V_c_U->if_dout(img_1_cols_V_c_dout);
    img_1_cols_V_c_U->if_empty_n(img_1_cols_V_c_empty_n);
    img_1_cols_V_c_U->if_read(Merge_U0_dst_cols_V_read);
    img_0_data_stream_0_U = new fifo_w8_d2_A("img_0_data_stream_0_U");
    img_0_data_stream_0_U->clk(ap_clk);
    img_0_data_stream_0_U->reset(ap_rst_n_inv);
    img_0_data_stream_0_U->if_read_ce(ap_var_for_const0);
    img_0_data_stream_0_U->if_write_ce(ap_var_for_const0);
    img_0_data_stream_0_U->if_din(AXIvideo2Mat_U0_img_data_stream_0_V_din);
    img_0_data_stream_0_U->if_full_n(img_0_data_stream_0_full_n);
    img_0_data_stream_0_U->if_write(AXIvideo2Mat_U0_img_data_stream_0_V_write);
    img_0_data_stream_0_U->if_dout(img_0_data_stream_0_dout);
    img_0_data_stream_0_U->if_empty_n(img_0_data_stream_0_empty_n);
    img_0_data_stream_0_U->if_read(Split_U0_src_data_stream_0_V_read);
    img_0_data_stream_1_U = new fifo_w8_d2_A("img_0_data_stream_1_U");
    img_0_data_stream_1_U->clk(ap_clk);
    img_0_data_stream_1_U->reset(ap_rst_n_inv);
    img_0_data_stream_1_U->if_read_ce(ap_var_for_const0);
    img_0_data_stream_1_U->if_write_ce(ap_var_for_const0);
    img_0_data_stream_1_U->if_din(AXIvideo2Mat_U0_img_data_stream_1_V_din);
    img_0_data_stream_1_U->if_full_n(img_0_data_stream_1_full_n);
    img_0_data_stream_1_U->if_write(AXIvideo2Mat_U0_img_data_stream_1_V_write);
    img_0_data_stream_1_U->if_dout(img_0_data_stream_1_dout);
    img_0_data_stream_1_U->if_empty_n(img_0_data_stream_1_empty_n);
    img_0_data_stream_1_U->if_read(Split_U0_src_data_stream_1_V_read);
    img_0_data_stream_2_U = new fifo_w8_d2_A("img_0_data_stream_2_U");
    img_0_data_stream_2_U->clk(ap_clk);
    img_0_data_stream_2_U->reset(ap_rst_n_inv);
    img_0_data_stream_2_U->if_read_ce(ap_var_for_const0);
    img_0_data_stream_2_U->if_write_ce(ap_var_for_const0);
    img_0_data_stream_2_U->if_din(AXIvideo2Mat_U0_img_data_stream_2_V_din);
    img_0_data_stream_2_U->if_full_n(img_0_data_stream_2_full_n);
    img_0_data_stream_2_U->if_write(AXIvideo2Mat_U0_img_data_stream_2_V_write);
    img_0_data_stream_2_U->if_dout(img_0_data_stream_2_dout);
    img_0_data_stream_2_U->if_empty_n(img_0_data_stream_2_empty_n);
    img_0_data_stream_2_U->if_read(Split_U0_src_data_stream_2_V_read);
    img_0_rows_V_c20_U = new fifo_w10_d2_A("img_0_rows_V_c20_U");
    img_0_rows_V_c20_U->clk(ap_clk);
    img_0_rows_V_c20_U->reset(ap_rst_n_inv);
    img_0_rows_V_c20_U->if_read_ce(ap_var_for_const0);
    img_0_rows_V_c20_U->if_write_ce(ap_var_for_const0);
    img_0_rows_V_c20_U->if_din(AXIvideo2Mat_U0_img_rows_V_out_din);
    img_0_rows_V_c20_U->if_full_n(img_0_rows_V_c20_full_n);
    img_0_rows_V_c20_U->if_write(AXIvideo2Mat_U0_img_rows_V_out_write);
    img_0_rows_V_c20_U->if_dout(img_0_rows_V_c20_dout);
    img_0_rows_V_c20_U->if_empty_n(img_0_rows_V_c20_empty_n);
    img_0_rows_V_c20_U->if_read(Split_U0_src_rows_V_read);
    img_0_cols_V_c21_U = new fifo_w11_d2_A("img_0_cols_V_c21_U");
    img_0_cols_V_c21_U->clk(ap_clk);
    img_0_cols_V_c21_U->reset(ap_rst_n_inv);
    img_0_cols_V_c21_U->if_read_ce(ap_var_for_const0);
    img_0_cols_V_c21_U->if_write_ce(ap_var_for_const0);
    img_0_cols_V_c21_U->if_din(AXIvideo2Mat_U0_img_cols_V_out_din);
    img_0_cols_V_c21_U->if_full_n(img_0_cols_V_c21_full_n);
    img_0_cols_V_c21_U->if_write(AXIvideo2Mat_U0_img_cols_V_out_write);
    img_0_cols_V_c21_U->if_dout(img_0_cols_V_c21_dout);
    img_0_cols_V_c21_U->if_empty_n(img_0_cols_V_c21_empty_n);
    img_0_cols_V_c21_U->if_read(Split_U0_src_cols_V_read);
    img_B_data_stream_0_U = new fifo_w8_d2_A("img_B_data_stream_0_U");
    img_B_data_stream_0_U->clk(ap_clk);
    img_B_data_stream_0_U->reset(ap_rst_n_inv);
    img_B_data_stream_0_U->if_read_ce(ap_var_for_const0);
    img_B_data_stream_0_U->if_write_ce(ap_var_for_const0);
    img_B_data_stream_0_U->if_din(Split_U0_dst0_data_stream_V_din);
    img_B_data_stream_0_U->if_full_n(img_B_data_stream_0_full_n);
    img_B_data_stream_0_U->if_write(Split_U0_dst0_data_stream_V_write);
    img_B_data_stream_0_U->if_dout(img_B_data_stream_0_dout);
    img_B_data_stream_0_U->if_empty_n(img_B_data_stream_0_empty_n);
    img_B_data_stream_0_U->if_read(GaussianBlur162_U0_p_src_data_stream_V_read);
    img_G_data_stream_0_U = new fifo_w8_d2_A("img_G_data_stream_0_U");
    img_G_data_stream_0_U->clk(ap_clk);
    img_G_data_stream_0_U->reset(ap_rst_n_inv);
    img_G_data_stream_0_U->if_read_ce(ap_var_for_const0);
    img_G_data_stream_0_U->if_write_ce(ap_var_for_const0);
    img_G_data_stream_0_U->if_din(Split_U0_dst1_data_stream_V_din);
    img_G_data_stream_0_U->if_full_n(img_G_data_stream_0_full_n);
    img_G_data_stream_0_U->if_write(Split_U0_dst1_data_stream_V_write);
    img_G_data_stream_0_U->if_dout(img_G_data_stream_0_dout);
    img_G_data_stream_0_U->if_empty_n(img_G_data_stream_0_empty_n);
    img_G_data_stream_0_U->if_read(GaussianBlur163_U0_p_src_data_stream_V_read);
    img_R_data_stream_0_U = new fifo_w8_d2_A("img_R_data_stream_0_U");
    img_R_data_stream_0_U->clk(ap_clk);
    img_R_data_stream_0_U->reset(ap_rst_n_inv);
    img_R_data_stream_0_U->if_read_ce(ap_var_for_const0);
    img_R_data_stream_0_U->if_write_ce(ap_var_for_const0);
    img_R_data_stream_0_U->if_din(Split_U0_dst2_data_stream_V_din);
    img_R_data_stream_0_U->if_full_n(img_R_data_stream_0_full_n);
    img_R_data_stream_0_U->if_write(Split_U0_dst2_data_stream_V_write);
    img_R_data_stream_0_U->if_dout(img_R_data_stream_0_dout);
    img_R_data_stream_0_U->if_empty_n(img_R_data_stream_0_empty_n);
    img_R_data_stream_0_U->if_read(GaussianBlur_U0_p_src_data_stream_V_read);
    img_B_f_data_stream_s_U = new fifo_w8_d2_A("img_B_f_data_stream_s_U");
    img_B_f_data_stream_s_U->clk(ap_clk);
    img_B_f_data_stream_s_U->reset(ap_rst_n_inv);
    img_B_f_data_stream_s_U->if_read_ce(ap_var_for_const0);
    img_B_f_data_stream_s_U->if_write_ce(ap_var_for_const0);
    img_B_f_data_stream_s_U->if_din(GaussianBlur162_U0_p_dst_data_stream_V_din);
    img_B_f_data_stream_s_U->if_full_n(img_B_f_data_stream_s_full_n);
    img_B_f_data_stream_s_U->if_write(GaussianBlur162_U0_p_dst_data_stream_V_write);
    img_B_f_data_stream_s_U->if_dout(img_B_f_data_stream_s_dout);
    img_B_f_data_stream_s_U->if_empty_n(img_B_f_data_stream_s_empty_n);
    img_B_f_data_stream_s_U->if_read(Merge_U0_src0_data_stream_V_read);
    img_G_f_data_stream_s_U = new fifo_w8_d2_A("img_G_f_data_stream_s_U");
    img_G_f_data_stream_s_U->clk(ap_clk);
    img_G_f_data_stream_s_U->reset(ap_rst_n_inv);
    img_G_f_data_stream_s_U->if_read_ce(ap_var_for_const0);
    img_G_f_data_stream_s_U->if_write_ce(ap_var_for_const0);
    img_G_f_data_stream_s_U->if_din(GaussianBlur163_U0_p_dst_data_stream_V_din);
    img_G_f_data_stream_s_U->if_full_n(img_G_f_data_stream_s_full_n);
    img_G_f_data_stream_s_U->if_write(GaussianBlur163_U0_p_dst_data_stream_V_write);
    img_G_f_data_stream_s_U->if_dout(img_G_f_data_stream_s_dout);
    img_G_f_data_stream_s_U->if_empty_n(img_G_f_data_stream_s_empty_n);
    img_G_f_data_stream_s_U->if_read(Merge_U0_src1_data_stream_V_read);
    img_R_f_data_stream_s_U = new fifo_w8_d2_A("img_R_f_data_stream_s_U");
    img_R_f_data_stream_s_U->clk(ap_clk);
    img_R_f_data_stream_s_U->reset(ap_rst_n_inv);
    img_R_f_data_stream_s_U->if_read_ce(ap_var_for_const0);
    img_R_f_data_stream_s_U->if_write_ce(ap_var_for_const0);
    img_R_f_data_stream_s_U->if_din(GaussianBlur_U0_p_dst_data_stream_V_din);
    img_R_f_data_stream_s_U->if_full_n(img_R_f_data_stream_s_full_n);
    img_R_f_data_stream_s_U->if_write(GaussianBlur_U0_p_dst_data_stream_V_write);
    img_R_f_data_stream_s_U->if_dout(img_R_f_data_stream_s_dout);
    img_R_f_data_stream_s_U->if_empty_n(img_R_f_data_stream_s_empty_n);
    img_R_f_data_stream_s_U->if_read(Merge_U0_src2_data_stream_V_read);
    img_1_data_stream_0_U = new fifo_w8_d2_A("img_1_data_stream_0_U");
    img_1_data_stream_0_U->clk(ap_clk);
    img_1_data_stream_0_U->reset(ap_rst_n_inv);
    img_1_data_stream_0_U->if_read_ce(ap_var_for_const0);
    img_1_data_stream_0_U->if_write_ce(ap_var_for_const0);
    img_1_data_stream_0_U->if_din(Merge_U0_dst_data_stream_0_V_din);
    img_1_data_stream_0_U->if_full_n(img_1_data_stream_0_full_n);
    img_1_data_stream_0_U->if_write(Merge_U0_dst_data_stream_0_V_write);
    img_1_data_stream_0_U->if_dout(img_1_data_stream_0_dout);
    img_1_data_stream_0_U->if_empty_n(img_1_data_stream_0_empty_n);
    img_1_data_stream_0_U->if_read(Mat2AXIvideo_U0_img_data_stream_0_V_read);
    img_1_data_stream_1_U = new fifo_w8_d2_A("img_1_data_stream_1_U");
    img_1_data_stream_1_U->clk(ap_clk);
    img_1_data_stream_1_U->reset(ap_rst_n_inv);
    img_1_data_stream_1_U->if_read_ce(ap_var_for_const0);
    img_1_data_stream_1_U->if_write_ce(ap_var_for_const0);
    img_1_data_stream_1_U->if_din(Merge_U0_dst_data_stream_1_V_din);
    img_1_data_stream_1_U->if_full_n(img_1_data_stream_1_full_n);
    img_1_data_stream_1_U->if_write(Merge_U0_dst_data_stream_1_V_write);
    img_1_data_stream_1_U->if_dout(img_1_data_stream_1_dout);
    img_1_data_stream_1_U->if_empty_n(img_1_data_stream_1_empty_n);
    img_1_data_stream_1_U->if_read(Mat2AXIvideo_U0_img_data_stream_1_V_read);
    img_1_data_stream_2_U = new fifo_w8_d2_A("img_1_data_stream_2_U");
    img_1_data_stream_2_U->clk(ap_clk);
    img_1_data_stream_2_U->reset(ap_rst_n_inv);
    img_1_data_stream_2_U->if_read_ce(ap_var_for_const0);
    img_1_data_stream_2_U->if_write_ce(ap_var_for_const0);
    img_1_data_stream_2_U->if_din(Merge_U0_dst_data_stream_2_V_din);
    img_1_data_stream_2_U->if_full_n(img_1_data_stream_2_full_n);
    img_1_data_stream_2_U->if_write(Merge_U0_dst_data_stream_2_V_write);
    img_1_data_stream_2_U->if_dout(img_1_data_stream_2_dout);
    img_1_data_stream_2_U->if_empty_n(img_1_data_stream_2_empty_n);
    img_1_data_stream_2_U->if_read(Mat2AXIvideo_U0_img_data_stream_2_V_read);
    img_1_rows_V_c22_U = new fifo_w10_d2_A("img_1_rows_V_c22_U");
    img_1_rows_V_c22_U->clk(ap_clk);
    img_1_rows_V_c22_U->reset(ap_rst_n_inv);
    img_1_rows_V_c22_U->if_read_ce(ap_var_for_const0);
    img_1_rows_V_c22_U->if_write_ce(ap_var_for_const0);
    img_1_rows_V_c22_U->if_din(Merge_U0_dst_rows_V_out_din);
    img_1_rows_V_c22_U->if_full_n(img_1_rows_V_c22_full_n);
    img_1_rows_V_c22_U->if_write(Merge_U0_dst_rows_V_out_write);
    img_1_rows_V_c22_U->if_dout(img_1_rows_V_c22_dout);
    img_1_rows_V_c22_U->if_empty_n(img_1_rows_V_c22_empty_n);
    img_1_rows_V_c22_U->if_read(Mat2AXIvideo_U0_img_rows_V_read);
    img_1_cols_V_c23_U = new fifo_w11_d2_A("img_1_cols_V_c23_U");
    img_1_cols_V_c23_U->clk(ap_clk);
    img_1_cols_V_c23_U->reset(ap_rst_n_inv);
    img_1_cols_V_c23_U->if_read_ce(ap_var_for_const0);
    img_1_cols_V_c23_U->if_write_ce(ap_var_for_const0);
    img_1_cols_V_c23_U->if_din(Merge_U0_dst_cols_V_out_din);
    img_1_cols_V_c23_U->if_full_n(img_1_cols_V_c23_full_n);
    img_1_cols_V_c23_U->if_write(Merge_U0_dst_cols_V_out_write);
    img_1_cols_V_c23_U->if_dout(img_1_cols_V_c23_dout);
    img_1_cols_V_c23_U->if_empty_n(img_1_cols_V_c23_empty_n);
    img_1_cols_V_c23_U->if_read(Mat2AXIvideo_U0_img_cols_V_read);
    start_for_Merge_U0_U = new start_for_Merge_U0("start_for_Merge_U0_U");
    start_for_Merge_U0_U->clk(ap_clk);
    start_for_Merge_U0_U->reset(ap_rst_n_inv);
    start_for_Merge_U0_U->if_read_ce(ap_var_for_const0);
    start_for_Merge_U0_U->if_write_ce(ap_var_for_const0);
    start_for_Merge_U0_U->if_din(start_for_Merge_U0_din);
    start_for_Merge_U0_U->if_full_n(start_for_Merge_U0_full_n);
    start_for_Merge_U0_U->if_write(Block_proc_U0_start_write);
    start_for_Merge_U0_U->if_dout(start_for_Merge_U0_dout);
    start_for_Merge_U0_U->if_empty_n(start_for_Merge_U0_empty_n);
    start_for_Merge_U0_U->if_read(Merge_U0_ap_ready);
    start_for_Split_U0_U = new start_for_Split_U0("start_for_Split_U0_U");
    start_for_Split_U0_U->clk(ap_clk);
    start_for_Split_U0_U->reset(ap_rst_n_inv);
    start_for_Split_U0_U->if_read_ce(ap_var_for_const0);
    start_for_Split_U0_U->if_write_ce(ap_var_for_const0);
    start_for_Split_U0_U->if_din(start_for_Split_U0_din);
    start_for_Split_U0_U->if_full_n(start_for_Split_U0_full_n);
    start_for_Split_U0_U->if_write(AXIvideo2Mat_U0_start_write);
    start_for_Split_U0_U->if_dout(start_for_Split_U0_dout);
    start_for_Split_U0_U->if_empty_n(start_for_Split_U0_empty_n);
    start_for_Split_U0_U->if_read(Split_U0_ap_ready);
    start_for_GaussiajbC_U = new start_for_GaussiajbC("start_for_GaussiajbC_U");
    start_for_GaussiajbC_U->clk(ap_clk);
    start_for_GaussiajbC_U->reset(ap_rst_n_inv);
    start_for_GaussiajbC_U->if_read_ce(ap_var_for_const0);
    start_for_GaussiajbC_U->if_write_ce(ap_var_for_const0);
    start_for_GaussiajbC_U->if_din(start_for_GaussianBlur162_U0_din);
    start_for_GaussiajbC_U->if_full_n(start_for_GaussianBlur162_U0_full_n);
    start_for_GaussiajbC_U->if_write(Split_U0_start_write);
    start_for_GaussiajbC_U->if_dout(start_for_GaussianBlur162_U0_dout);
    start_for_GaussiajbC_U->if_empty_n(start_for_GaussianBlur162_U0_empty_n);
    start_for_GaussiajbC_U->if_read(GaussianBlur162_U0_ap_ready);
    start_for_GaussiakbM_U = new start_for_GaussiakbM("start_for_GaussiakbM_U");
    start_for_GaussiakbM_U->clk(ap_clk);
    start_for_GaussiakbM_U->reset(ap_rst_n_inv);
    start_for_GaussiakbM_U->if_read_ce(ap_var_for_const0);
    start_for_GaussiakbM_U->if_write_ce(ap_var_for_const0);
    start_for_GaussiakbM_U->if_din(start_for_GaussianBlur163_U0_din);
    start_for_GaussiakbM_U->if_full_n(start_for_GaussianBlur163_U0_full_n);
    start_for_GaussiakbM_U->if_write(Split_U0_start_write);
    start_for_GaussiakbM_U->if_dout(start_for_GaussianBlur163_U0_dout);
    start_for_GaussiakbM_U->if_empty_n(start_for_GaussianBlur163_U0_empty_n);
    start_for_GaussiakbM_U->if_read(GaussianBlur163_U0_ap_ready);
    start_for_GaussialbW_U = new start_for_GaussialbW("start_for_GaussialbW_U");
    start_for_GaussialbW_U->clk(ap_clk);
    start_for_GaussialbW_U->reset(ap_rst_n_inv);
    start_for_GaussialbW_U->if_read_ce(ap_var_for_const0);
    start_for_GaussialbW_U->if_write_ce(ap_var_for_const0);
    start_for_GaussialbW_U->if_din(start_for_GaussianBlur_U0_din);
    start_for_GaussialbW_U->if_full_n(start_for_GaussianBlur_U0_full_n);
    start_for_GaussialbW_U->if_write(Split_U0_start_write);
    start_for_GaussialbW_U->if_dout(start_for_GaussianBlur_U0_dout);
    start_for_GaussialbW_U->if_empty_n(start_for_GaussianBlur_U0_empty_n);
    start_for_GaussialbW_U->if_read(GaussianBlur_U0_ap_ready);
    start_for_Mat2AXImb6_U = new start_for_Mat2AXImb6("start_for_Mat2AXImb6_U");
    start_for_Mat2AXImb6_U->clk(ap_clk);
    start_for_Mat2AXImb6_U->reset(ap_rst_n_inv);
    start_for_Mat2AXImb6_U->if_read_ce(ap_var_for_const0);
    start_for_Mat2AXImb6_U->if_write_ce(ap_var_for_const0);
    start_for_Mat2AXImb6_U->if_din(start_for_Mat2AXIvideo_U0_din);
    start_for_Mat2AXImb6_U->if_full_n(start_for_Mat2AXIvideo_U0_full_n);
    start_for_Mat2AXImb6_U->if_write(Merge_U0_start_write);
    start_for_Mat2AXImb6_U->if_dout(start_for_Mat2AXIvideo_U0_dout);
    start_for_Mat2AXImb6_U->if_empty_n(start_for_Mat2AXIvideo_U0_empty_n);
    start_for_Mat2AXImb6_U->if_read(Mat2AXIvideo_U0_ap_ready);

    SC_METHOD(thread_AXIvideo2Mat_U0_ap_continue);

    SC_METHOD(thread_AXIvideo2Mat_U0_ap_start);

    SC_METHOD(thread_Block_proc_U0_ap_continue);

    SC_METHOD(thread_Block_proc_U0_ap_start);

    SC_METHOD(thread_GaussianBlur162_U0_ap_continue);

    SC_METHOD(thread_GaussianBlur162_U0_ap_start);
    sensitive << ( start_for_GaussianBlur162_U0_empty_n );

    SC_METHOD(thread_GaussianBlur162_U0_start_full_n);

    SC_METHOD(thread_GaussianBlur162_U0_start_write);

    SC_METHOD(thread_GaussianBlur163_U0_ap_continue);

    SC_METHOD(thread_GaussianBlur163_U0_ap_start);
    sensitive << ( start_for_GaussianBlur163_U0_empty_n );

    SC_METHOD(thread_GaussianBlur163_U0_start_full_n);

    SC_METHOD(thread_GaussianBlur163_U0_start_write);

    SC_METHOD(thread_GaussianBlur_U0_ap_continue);

    SC_METHOD(thread_GaussianBlur_U0_ap_start);
    sensitive << ( start_for_GaussianBlur_U0_empty_n );

    SC_METHOD(thread_GaussianBlur_U0_start_full_n);

    SC_METHOD(thread_GaussianBlur_U0_start_write);

    SC_METHOD(thread_INPUT_STREAM_TREADY);
    sensitive << ( AXIvideo2Mat_U0_INPUT_STREAM_TREADY );

    SC_METHOD(thread_Mat2AXIvideo_U0_ap_continue);

    SC_METHOD(thread_Mat2AXIvideo_U0_ap_start);
    sensitive << ( start_for_Mat2AXIvideo_U0_empty_n );

    SC_METHOD(thread_Mat2AXIvideo_U0_start_full_n);

    SC_METHOD(thread_Mat2AXIvideo_U0_start_write);

    SC_METHOD(thread_Merge_U0_ap_continue);

    SC_METHOD(thread_Merge_U0_ap_start);
    sensitive << ( start_for_Merge_U0_empty_n );

    SC_METHOD(thread_OUTPUT_STREAM_TDATA);
    sensitive << ( Mat2AXIvideo_U0_OUTPUT_STREAM_TDATA );

    SC_METHOD(thread_OUTPUT_STREAM_TDEST);
    sensitive << ( Mat2AXIvideo_U0_OUTPUT_STREAM_TDEST );

    SC_METHOD(thread_OUTPUT_STREAM_TID);
    sensitive << ( Mat2AXIvideo_U0_OUTPUT_STREAM_TID );

    SC_METHOD(thread_OUTPUT_STREAM_TKEEP);
    sensitive << ( Mat2AXIvideo_U0_OUTPUT_STREAM_TKEEP );

    SC_METHOD(thread_OUTPUT_STREAM_TLAST);
    sensitive << ( Mat2AXIvideo_U0_OUTPUT_STREAM_TLAST );

    SC_METHOD(thread_OUTPUT_STREAM_TSTRB);
    sensitive << ( Mat2AXIvideo_U0_OUTPUT_STREAM_TSTRB );

    SC_METHOD(thread_OUTPUT_STREAM_TUSER);
    sensitive << ( Mat2AXIvideo_U0_OUTPUT_STREAM_TUSER );

    SC_METHOD(thread_OUTPUT_STREAM_TVALID);
    sensitive << ( Mat2AXIvideo_U0_OUTPUT_STREAM_TVALID );

    SC_METHOD(thread_Split_U0_ap_continue);

    SC_METHOD(thread_Split_U0_ap_start);
    sensitive << ( start_for_Split_U0_empty_n );

    SC_METHOD(thread_Split_U0_start_full_n);
    sensitive << ( start_for_GaussianBlur162_U0_full_n );
    sensitive << ( start_for_GaussianBlur163_U0_full_n );
    sensitive << ( start_for_GaussianBlur_U0_full_n );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_ap_sync_continue);

    SC_METHOD(thread_start_for_GaussianBlur162_U0_din);

    SC_METHOD(thread_start_for_GaussianBlur163_U0_din);

    SC_METHOD(thread_start_for_GaussianBlur_U0_din);

    SC_METHOD(thread_start_for_Mat2AXIvideo_U0_din);

    SC_METHOD(thread_start_for_Merge_U0_din);

    SC_METHOD(thread_start_for_Split_U0_din);

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "ov5640_GaussianBlur_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, INPUT_STREAM_TDATA, "(port)INPUT_STREAM_TDATA");
    sc_trace(mVcdFile, INPUT_STREAM_TKEEP, "(port)INPUT_STREAM_TKEEP");
    sc_trace(mVcdFile, INPUT_STREAM_TSTRB, "(port)INPUT_STREAM_TSTRB");
    sc_trace(mVcdFile, INPUT_STREAM_TUSER, "(port)INPUT_STREAM_TUSER");
    sc_trace(mVcdFile, INPUT_STREAM_TLAST, "(port)INPUT_STREAM_TLAST");
    sc_trace(mVcdFile, INPUT_STREAM_TID, "(port)INPUT_STREAM_TID");
    sc_trace(mVcdFile, INPUT_STREAM_TDEST, "(port)INPUT_STREAM_TDEST");
    sc_trace(mVcdFile, OUTPUT_STREAM_TDATA, "(port)OUTPUT_STREAM_TDATA");
    sc_trace(mVcdFile, OUTPUT_STREAM_TKEEP, "(port)OUTPUT_STREAM_TKEEP");
    sc_trace(mVcdFile, OUTPUT_STREAM_TSTRB, "(port)OUTPUT_STREAM_TSTRB");
    sc_trace(mVcdFile, OUTPUT_STREAM_TUSER, "(port)OUTPUT_STREAM_TUSER");
    sc_trace(mVcdFile, OUTPUT_STREAM_TLAST, "(port)OUTPUT_STREAM_TLAST");
    sc_trace(mVcdFile, OUTPUT_STREAM_TID, "(port)OUTPUT_STREAM_TID");
    sc_trace(mVcdFile, OUTPUT_STREAM_TDEST, "(port)OUTPUT_STREAM_TDEST");
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, INPUT_STREAM_TVALID, "(port)INPUT_STREAM_TVALID");
    sc_trace(mVcdFile, INPUT_STREAM_TREADY, "(port)INPUT_STREAM_TREADY");
    sc_trace(mVcdFile, OUTPUT_STREAM_TVALID, "(port)OUTPUT_STREAM_TVALID");
    sc_trace(mVcdFile, OUTPUT_STREAM_TREADY, "(port)OUTPUT_STREAM_TREADY");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, Block_proc_U0_ap_start, "Block_proc_U0_ap_start");
    sc_trace(mVcdFile, Block_proc_U0_ap_done, "Block_proc_U0_ap_done");
    sc_trace(mVcdFile, Block_proc_U0_ap_continue, "Block_proc_U0_ap_continue");
    sc_trace(mVcdFile, Block_proc_U0_ap_idle, "Block_proc_U0_ap_idle");
    sc_trace(mVcdFile, Block_proc_U0_ap_ready, "Block_proc_U0_ap_ready");
    sc_trace(mVcdFile, Block_proc_U0_start_out, "Block_proc_U0_start_out");
    sc_trace(mVcdFile, Block_proc_U0_start_write, "Block_proc_U0_start_write");
    sc_trace(mVcdFile, Block_proc_U0_img_0_rows_V_out_din, "Block_proc_U0_img_0_rows_V_out_din");
    sc_trace(mVcdFile, Block_proc_U0_img_0_rows_V_out_write, "Block_proc_U0_img_0_rows_V_out_write");
    sc_trace(mVcdFile, Block_proc_U0_img_0_cols_V_out_din, "Block_proc_U0_img_0_cols_V_out_din");
    sc_trace(mVcdFile, Block_proc_U0_img_0_cols_V_out_write, "Block_proc_U0_img_0_cols_V_out_write");
    sc_trace(mVcdFile, Block_proc_U0_img_1_rows_V_out_din, "Block_proc_U0_img_1_rows_V_out_din");
    sc_trace(mVcdFile, Block_proc_U0_img_1_rows_V_out_write, "Block_proc_U0_img_1_rows_V_out_write");
    sc_trace(mVcdFile, Block_proc_U0_img_1_cols_V_out_din, "Block_proc_U0_img_1_cols_V_out_din");
    sc_trace(mVcdFile, Block_proc_U0_img_1_cols_V_out_write, "Block_proc_U0_img_1_cols_V_out_write");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_ap_start, "AXIvideo2Mat_U0_ap_start");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_ap_done, "AXIvideo2Mat_U0_ap_done");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_ap_continue, "AXIvideo2Mat_U0_ap_continue");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_ap_idle, "AXIvideo2Mat_U0_ap_idle");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_ap_ready, "AXIvideo2Mat_U0_ap_ready");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_start_out, "AXIvideo2Mat_U0_start_out");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_start_write, "AXIvideo2Mat_U0_start_write");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_INPUT_STREAM_TREADY, "AXIvideo2Mat_U0_INPUT_STREAM_TREADY");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_rows_V_read, "AXIvideo2Mat_U0_img_rows_V_read");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_cols_V_read, "AXIvideo2Mat_U0_img_cols_V_read");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_data_stream_0_V_din, "AXIvideo2Mat_U0_img_data_stream_0_V_din");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_data_stream_0_V_write, "AXIvideo2Mat_U0_img_data_stream_0_V_write");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_data_stream_1_V_din, "AXIvideo2Mat_U0_img_data_stream_1_V_din");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_data_stream_1_V_write, "AXIvideo2Mat_U0_img_data_stream_1_V_write");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_data_stream_2_V_din, "AXIvideo2Mat_U0_img_data_stream_2_V_din");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_data_stream_2_V_write, "AXIvideo2Mat_U0_img_data_stream_2_V_write");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_rows_V_out_din, "AXIvideo2Mat_U0_img_rows_V_out_din");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_rows_V_out_write, "AXIvideo2Mat_U0_img_rows_V_out_write");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_cols_V_out_din, "AXIvideo2Mat_U0_img_cols_V_out_din");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_cols_V_out_write, "AXIvideo2Mat_U0_img_cols_V_out_write");
    sc_trace(mVcdFile, Split_U0_ap_start, "Split_U0_ap_start");
    sc_trace(mVcdFile, Split_U0_start_full_n, "Split_U0_start_full_n");
    sc_trace(mVcdFile, Split_U0_ap_done, "Split_U0_ap_done");
    sc_trace(mVcdFile, Split_U0_ap_continue, "Split_U0_ap_continue");
    sc_trace(mVcdFile, Split_U0_ap_idle, "Split_U0_ap_idle");
    sc_trace(mVcdFile, Split_U0_ap_ready, "Split_U0_ap_ready");
    sc_trace(mVcdFile, Split_U0_start_out, "Split_U0_start_out");
    sc_trace(mVcdFile, Split_U0_start_write, "Split_U0_start_write");
    sc_trace(mVcdFile, Split_U0_src_rows_V_read, "Split_U0_src_rows_V_read");
    sc_trace(mVcdFile, Split_U0_src_cols_V_read, "Split_U0_src_cols_V_read");
    sc_trace(mVcdFile, Split_U0_src_data_stream_0_V_read, "Split_U0_src_data_stream_0_V_read");
    sc_trace(mVcdFile, Split_U0_src_data_stream_1_V_read, "Split_U0_src_data_stream_1_V_read");
    sc_trace(mVcdFile, Split_U0_src_data_stream_2_V_read, "Split_U0_src_data_stream_2_V_read");
    sc_trace(mVcdFile, Split_U0_dst0_data_stream_V_din, "Split_U0_dst0_data_stream_V_din");
    sc_trace(mVcdFile, Split_U0_dst0_data_stream_V_write, "Split_U0_dst0_data_stream_V_write");
    sc_trace(mVcdFile, Split_U0_dst1_data_stream_V_din, "Split_U0_dst1_data_stream_V_din");
    sc_trace(mVcdFile, Split_U0_dst1_data_stream_V_write, "Split_U0_dst1_data_stream_V_write");
    sc_trace(mVcdFile, Split_U0_dst2_data_stream_V_din, "Split_U0_dst2_data_stream_V_din");
    sc_trace(mVcdFile, Split_U0_dst2_data_stream_V_write, "Split_U0_dst2_data_stream_V_write");
    sc_trace(mVcdFile, GaussianBlur162_U0_ap_start, "GaussianBlur162_U0_ap_start");
    sc_trace(mVcdFile, GaussianBlur162_U0_ap_done, "GaussianBlur162_U0_ap_done");
    sc_trace(mVcdFile, GaussianBlur162_U0_ap_continue, "GaussianBlur162_U0_ap_continue");
    sc_trace(mVcdFile, GaussianBlur162_U0_ap_idle, "GaussianBlur162_U0_ap_idle");
    sc_trace(mVcdFile, GaussianBlur162_U0_ap_ready, "GaussianBlur162_U0_ap_ready");
    sc_trace(mVcdFile, GaussianBlur162_U0_p_src_data_stream_V_read, "GaussianBlur162_U0_p_src_data_stream_V_read");
    sc_trace(mVcdFile, GaussianBlur162_U0_p_dst_data_stream_V_din, "GaussianBlur162_U0_p_dst_data_stream_V_din");
    sc_trace(mVcdFile, GaussianBlur162_U0_p_dst_data_stream_V_write, "GaussianBlur162_U0_p_dst_data_stream_V_write");
    sc_trace(mVcdFile, GaussianBlur163_U0_ap_start, "GaussianBlur163_U0_ap_start");
    sc_trace(mVcdFile, GaussianBlur163_U0_ap_done, "GaussianBlur163_U0_ap_done");
    sc_trace(mVcdFile, GaussianBlur163_U0_ap_continue, "GaussianBlur163_U0_ap_continue");
    sc_trace(mVcdFile, GaussianBlur163_U0_ap_idle, "GaussianBlur163_U0_ap_idle");
    sc_trace(mVcdFile, GaussianBlur163_U0_ap_ready, "GaussianBlur163_U0_ap_ready");
    sc_trace(mVcdFile, GaussianBlur163_U0_p_src_data_stream_V_read, "GaussianBlur163_U0_p_src_data_stream_V_read");
    sc_trace(mVcdFile, GaussianBlur163_U0_p_dst_data_stream_V_din, "GaussianBlur163_U0_p_dst_data_stream_V_din");
    sc_trace(mVcdFile, GaussianBlur163_U0_p_dst_data_stream_V_write, "GaussianBlur163_U0_p_dst_data_stream_V_write");
    sc_trace(mVcdFile, GaussianBlur_U0_ap_start, "GaussianBlur_U0_ap_start");
    sc_trace(mVcdFile, GaussianBlur_U0_ap_done, "GaussianBlur_U0_ap_done");
    sc_trace(mVcdFile, GaussianBlur_U0_ap_continue, "GaussianBlur_U0_ap_continue");
    sc_trace(mVcdFile, GaussianBlur_U0_ap_idle, "GaussianBlur_U0_ap_idle");
    sc_trace(mVcdFile, GaussianBlur_U0_ap_ready, "GaussianBlur_U0_ap_ready");
    sc_trace(mVcdFile, GaussianBlur_U0_p_src_data_stream_V_read, "GaussianBlur_U0_p_src_data_stream_V_read");
    sc_trace(mVcdFile, GaussianBlur_U0_p_dst_data_stream_V_din, "GaussianBlur_U0_p_dst_data_stream_V_din");
    sc_trace(mVcdFile, GaussianBlur_U0_p_dst_data_stream_V_write, "GaussianBlur_U0_p_dst_data_stream_V_write");
    sc_trace(mVcdFile, Merge_U0_ap_start, "Merge_U0_ap_start");
    sc_trace(mVcdFile, Merge_U0_ap_done, "Merge_U0_ap_done");
    sc_trace(mVcdFile, Merge_U0_ap_continue, "Merge_U0_ap_continue");
    sc_trace(mVcdFile, Merge_U0_ap_idle, "Merge_U0_ap_idle");
    sc_trace(mVcdFile, Merge_U0_ap_ready, "Merge_U0_ap_ready");
    sc_trace(mVcdFile, Merge_U0_start_out, "Merge_U0_start_out");
    sc_trace(mVcdFile, Merge_U0_start_write, "Merge_U0_start_write");
    sc_trace(mVcdFile, Merge_U0_src0_data_stream_V_read, "Merge_U0_src0_data_stream_V_read");
    sc_trace(mVcdFile, Merge_U0_src1_data_stream_V_read, "Merge_U0_src1_data_stream_V_read");
    sc_trace(mVcdFile, Merge_U0_src2_data_stream_V_read, "Merge_U0_src2_data_stream_V_read");
    sc_trace(mVcdFile, Merge_U0_dst_rows_V_read, "Merge_U0_dst_rows_V_read");
    sc_trace(mVcdFile, Merge_U0_dst_cols_V_read, "Merge_U0_dst_cols_V_read");
    sc_trace(mVcdFile, Merge_U0_dst_data_stream_0_V_din, "Merge_U0_dst_data_stream_0_V_din");
    sc_trace(mVcdFile, Merge_U0_dst_data_stream_0_V_write, "Merge_U0_dst_data_stream_0_V_write");
    sc_trace(mVcdFile, Merge_U0_dst_data_stream_1_V_din, "Merge_U0_dst_data_stream_1_V_din");
    sc_trace(mVcdFile, Merge_U0_dst_data_stream_1_V_write, "Merge_U0_dst_data_stream_1_V_write");
    sc_trace(mVcdFile, Merge_U0_dst_data_stream_2_V_din, "Merge_U0_dst_data_stream_2_V_din");
    sc_trace(mVcdFile, Merge_U0_dst_data_stream_2_V_write, "Merge_U0_dst_data_stream_2_V_write");
    sc_trace(mVcdFile, Merge_U0_dst_rows_V_out_din, "Merge_U0_dst_rows_V_out_din");
    sc_trace(mVcdFile, Merge_U0_dst_rows_V_out_write, "Merge_U0_dst_rows_V_out_write");
    sc_trace(mVcdFile, Merge_U0_dst_cols_V_out_din, "Merge_U0_dst_cols_V_out_din");
    sc_trace(mVcdFile, Merge_U0_dst_cols_V_out_write, "Merge_U0_dst_cols_V_out_write");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_ap_start, "Mat2AXIvideo_U0_ap_start");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_ap_done, "Mat2AXIvideo_U0_ap_done");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_ap_continue, "Mat2AXIvideo_U0_ap_continue");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_ap_idle, "Mat2AXIvideo_U0_ap_idle");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_ap_ready, "Mat2AXIvideo_U0_ap_ready");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_img_rows_V_read, "Mat2AXIvideo_U0_img_rows_V_read");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_img_cols_V_read, "Mat2AXIvideo_U0_img_cols_V_read");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_img_data_stream_0_V_read, "Mat2AXIvideo_U0_img_data_stream_0_V_read");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_img_data_stream_1_V_read, "Mat2AXIvideo_U0_img_data_stream_1_V_read");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_img_data_stream_2_V_read, "Mat2AXIvideo_U0_img_data_stream_2_V_read");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_OUTPUT_STREAM_TDATA, "Mat2AXIvideo_U0_OUTPUT_STREAM_TDATA");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_OUTPUT_STREAM_TVALID, "Mat2AXIvideo_U0_OUTPUT_STREAM_TVALID");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_OUTPUT_STREAM_TKEEP, "Mat2AXIvideo_U0_OUTPUT_STREAM_TKEEP");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_OUTPUT_STREAM_TSTRB, "Mat2AXIvideo_U0_OUTPUT_STREAM_TSTRB");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_OUTPUT_STREAM_TUSER, "Mat2AXIvideo_U0_OUTPUT_STREAM_TUSER");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_OUTPUT_STREAM_TLAST, "Mat2AXIvideo_U0_OUTPUT_STREAM_TLAST");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_OUTPUT_STREAM_TID, "Mat2AXIvideo_U0_OUTPUT_STREAM_TID");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_OUTPUT_STREAM_TDEST, "Mat2AXIvideo_U0_OUTPUT_STREAM_TDEST");
    sc_trace(mVcdFile, ap_sync_continue, "ap_sync_continue");
    sc_trace(mVcdFile, img_0_rows_V_c_full_n, "img_0_rows_V_c_full_n");
    sc_trace(mVcdFile, img_0_rows_V_c_dout, "img_0_rows_V_c_dout");
    sc_trace(mVcdFile, img_0_rows_V_c_empty_n, "img_0_rows_V_c_empty_n");
    sc_trace(mVcdFile, img_0_cols_V_c_full_n, "img_0_cols_V_c_full_n");
    sc_trace(mVcdFile, img_0_cols_V_c_dout, "img_0_cols_V_c_dout");
    sc_trace(mVcdFile, img_0_cols_V_c_empty_n, "img_0_cols_V_c_empty_n");
    sc_trace(mVcdFile, img_1_rows_V_c_full_n, "img_1_rows_V_c_full_n");
    sc_trace(mVcdFile, img_1_rows_V_c_dout, "img_1_rows_V_c_dout");
    sc_trace(mVcdFile, img_1_rows_V_c_empty_n, "img_1_rows_V_c_empty_n");
    sc_trace(mVcdFile, img_1_cols_V_c_full_n, "img_1_cols_V_c_full_n");
    sc_trace(mVcdFile, img_1_cols_V_c_dout, "img_1_cols_V_c_dout");
    sc_trace(mVcdFile, img_1_cols_V_c_empty_n, "img_1_cols_V_c_empty_n");
    sc_trace(mVcdFile, img_0_data_stream_0_full_n, "img_0_data_stream_0_full_n");
    sc_trace(mVcdFile, img_0_data_stream_0_dout, "img_0_data_stream_0_dout");
    sc_trace(mVcdFile, img_0_data_stream_0_empty_n, "img_0_data_stream_0_empty_n");
    sc_trace(mVcdFile, img_0_data_stream_1_full_n, "img_0_data_stream_1_full_n");
    sc_trace(mVcdFile, img_0_data_stream_1_dout, "img_0_data_stream_1_dout");
    sc_trace(mVcdFile, img_0_data_stream_1_empty_n, "img_0_data_stream_1_empty_n");
    sc_trace(mVcdFile, img_0_data_stream_2_full_n, "img_0_data_stream_2_full_n");
    sc_trace(mVcdFile, img_0_data_stream_2_dout, "img_0_data_stream_2_dout");
    sc_trace(mVcdFile, img_0_data_stream_2_empty_n, "img_0_data_stream_2_empty_n");
    sc_trace(mVcdFile, img_0_rows_V_c20_full_n, "img_0_rows_V_c20_full_n");
    sc_trace(mVcdFile, img_0_rows_V_c20_dout, "img_0_rows_V_c20_dout");
    sc_trace(mVcdFile, img_0_rows_V_c20_empty_n, "img_0_rows_V_c20_empty_n");
    sc_trace(mVcdFile, img_0_cols_V_c21_full_n, "img_0_cols_V_c21_full_n");
    sc_trace(mVcdFile, img_0_cols_V_c21_dout, "img_0_cols_V_c21_dout");
    sc_trace(mVcdFile, img_0_cols_V_c21_empty_n, "img_0_cols_V_c21_empty_n");
    sc_trace(mVcdFile, img_B_data_stream_0_full_n, "img_B_data_stream_0_full_n");
    sc_trace(mVcdFile, img_B_data_stream_0_dout, "img_B_data_stream_0_dout");
    sc_trace(mVcdFile, img_B_data_stream_0_empty_n, "img_B_data_stream_0_empty_n");
    sc_trace(mVcdFile, img_G_data_stream_0_full_n, "img_G_data_stream_0_full_n");
    sc_trace(mVcdFile, img_G_data_stream_0_dout, "img_G_data_stream_0_dout");
    sc_trace(mVcdFile, img_G_data_stream_0_empty_n, "img_G_data_stream_0_empty_n");
    sc_trace(mVcdFile, img_R_data_stream_0_full_n, "img_R_data_stream_0_full_n");
    sc_trace(mVcdFile, img_R_data_stream_0_dout, "img_R_data_stream_0_dout");
    sc_trace(mVcdFile, img_R_data_stream_0_empty_n, "img_R_data_stream_0_empty_n");
    sc_trace(mVcdFile, img_B_f_data_stream_s_full_n, "img_B_f_data_stream_s_full_n");
    sc_trace(mVcdFile, img_B_f_data_stream_s_dout, "img_B_f_data_stream_s_dout");
    sc_trace(mVcdFile, img_B_f_data_stream_s_empty_n, "img_B_f_data_stream_s_empty_n");
    sc_trace(mVcdFile, img_G_f_data_stream_s_full_n, "img_G_f_data_stream_s_full_n");
    sc_trace(mVcdFile, img_G_f_data_stream_s_dout, "img_G_f_data_stream_s_dout");
    sc_trace(mVcdFile, img_G_f_data_stream_s_empty_n, "img_G_f_data_stream_s_empty_n");
    sc_trace(mVcdFile, img_R_f_data_stream_s_full_n, "img_R_f_data_stream_s_full_n");
    sc_trace(mVcdFile, img_R_f_data_stream_s_dout, "img_R_f_data_stream_s_dout");
    sc_trace(mVcdFile, img_R_f_data_stream_s_empty_n, "img_R_f_data_stream_s_empty_n");
    sc_trace(mVcdFile, img_1_data_stream_0_full_n, "img_1_data_stream_0_full_n");
    sc_trace(mVcdFile, img_1_data_stream_0_dout, "img_1_data_stream_0_dout");
    sc_trace(mVcdFile, img_1_data_stream_0_empty_n, "img_1_data_stream_0_empty_n");
    sc_trace(mVcdFile, img_1_data_stream_1_full_n, "img_1_data_stream_1_full_n");
    sc_trace(mVcdFile, img_1_data_stream_1_dout, "img_1_data_stream_1_dout");
    sc_trace(mVcdFile, img_1_data_stream_1_empty_n, "img_1_data_stream_1_empty_n");
    sc_trace(mVcdFile, img_1_data_stream_2_full_n, "img_1_data_stream_2_full_n");
    sc_trace(mVcdFile, img_1_data_stream_2_dout, "img_1_data_stream_2_dout");
    sc_trace(mVcdFile, img_1_data_stream_2_empty_n, "img_1_data_stream_2_empty_n");
    sc_trace(mVcdFile, img_1_rows_V_c22_full_n, "img_1_rows_V_c22_full_n");
    sc_trace(mVcdFile, img_1_rows_V_c22_dout, "img_1_rows_V_c22_dout");
    sc_trace(mVcdFile, img_1_rows_V_c22_empty_n, "img_1_rows_V_c22_empty_n");
    sc_trace(mVcdFile, img_1_cols_V_c23_full_n, "img_1_cols_V_c23_full_n");
    sc_trace(mVcdFile, img_1_cols_V_c23_dout, "img_1_cols_V_c23_dout");
    sc_trace(mVcdFile, img_1_cols_V_c23_empty_n, "img_1_cols_V_c23_empty_n");
    sc_trace(mVcdFile, start_for_Merge_U0_din, "start_for_Merge_U0_din");
    sc_trace(mVcdFile, start_for_Merge_U0_full_n, "start_for_Merge_U0_full_n");
    sc_trace(mVcdFile, start_for_Merge_U0_dout, "start_for_Merge_U0_dout");
    sc_trace(mVcdFile, start_for_Merge_U0_empty_n, "start_for_Merge_U0_empty_n");
    sc_trace(mVcdFile, start_for_Split_U0_din, "start_for_Split_U0_din");
    sc_trace(mVcdFile, start_for_Split_U0_full_n, "start_for_Split_U0_full_n");
    sc_trace(mVcdFile, start_for_Split_U0_dout, "start_for_Split_U0_dout");
    sc_trace(mVcdFile, start_for_Split_U0_empty_n, "start_for_Split_U0_empty_n");
    sc_trace(mVcdFile, start_for_GaussianBlur162_U0_din, "start_for_GaussianBlur162_U0_din");
    sc_trace(mVcdFile, start_for_GaussianBlur162_U0_full_n, "start_for_GaussianBlur162_U0_full_n");
    sc_trace(mVcdFile, start_for_GaussianBlur162_U0_dout, "start_for_GaussianBlur162_U0_dout");
    sc_trace(mVcdFile, start_for_GaussianBlur162_U0_empty_n, "start_for_GaussianBlur162_U0_empty_n");
    sc_trace(mVcdFile, start_for_GaussianBlur163_U0_din, "start_for_GaussianBlur163_U0_din");
    sc_trace(mVcdFile, start_for_GaussianBlur163_U0_full_n, "start_for_GaussianBlur163_U0_full_n");
    sc_trace(mVcdFile, start_for_GaussianBlur163_U0_dout, "start_for_GaussianBlur163_U0_dout");
    sc_trace(mVcdFile, start_for_GaussianBlur163_U0_empty_n, "start_for_GaussianBlur163_U0_empty_n");
    sc_trace(mVcdFile, start_for_GaussianBlur_U0_din, "start_for_GaussianBlur_U0_din");
    sc_trace(mVcdFile, start_for_GaussianBlur_U0_full_n, "start_for_GaussianBlur_U0_full_n");
    sc_trace(mVcdFile, start_for_GaussianBlur_U0_dout, "start_for_GaussianBlur_U0_dout");
    sc_trace(mVcdFile, start_for_GaussianBlur_U0_empty_n, "start_for_GaussianBlur_U0_empty_n");
    sc_trace(mVcdFile, GaussianBlur162_U0_start_full_n, "GaussianBlur162_U0_start_full_n");
    sc_trace(mVcdFile, GaussianBlur162_U0_start_write, "GaussianBlur162_U0_start_write");
    sc_trace(mVcdFile, GaussianBlur163_U0_start_full_n, "GaussianBlur163_U0_start_full_n");
    sc_trace(mVcdFile, GaussianBlur163_U0_start_write, "GaussianBlur163_U0_start_write");
    sc_trace(mVcdFile, GaussianBlur_U0_start_full_n, "GaussianBlur_U0_start_full_n");
    sc_trace(mVcdFile, GaussianBlur_U0_start_write, "GaussianBlur_U0_start_write");
    sc_trace(mVcdFile, start_for_Mat2AXIvideo_U0_din, "start_for_Mat2AXIvideo_U0_din");
    sc_trace(mVcdFile, start_for_Mat2AXIvideo_U0_full_n, "start_for_Mat2AXIvideo_U0_full_n");
    sc_trace(mVcdFile, start_for_Mat2AXIvideo_U0_dout, "start_for_Mat2AXIvideo_U0_dout");
    sc_trace(mVcdFile, start_for_Mat2AXIvideo_U0_empty_n, "start_for_Mat2AXIvideo_U0_empty_n");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_start_full_n, "Mat2AXIvideo_U0_start_full_n");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_start_write, "Mat2AXIvideo_U0_start_write");
#endif

    }
    mHdltvinHandle.open("ov5640_GaussianBlur.hdltvin.dat");
    mHdltvoutHandle.open("ov5640_GaussianBlur.hdltvout.dat");
}

ov5640_GaussianBlur::~ov5640_GaussianBlur() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete Block_proc_U0;
    delete AXIvideo2Mat_U0;
    delete Split_U0;
    delete GaussianBlur162_U0;
    delete GaussianBlur163_U0;
    delete GaussianBlur_U0;
    delete Merge_U0;
    delete Mat2AXIvideo_U0;
    delete img_0_rows_V_c_U;
    delete img_0_cols_V_c_U;
    delete img_1_rows_V_c_U;
    delete img_1_cols_V_c_U;
    delete img_0_data_stream_0_U;
    delete img_0_data_stream_1_U;
    delete img_0_data_stream_2_U;
    delete img_0_rows_V_c20_U;
    delete img_0_cols_V_c21_U;
    delete img_B_data_stream_0_U;
    delete img_G_data_stream_0_U;
    delete img_R_data_stream_0_U;
    delete img_B_f_data_stream_s_U;
    delete img_G_f_data_stream_s_U;
    delete img_R_f_data_stream_s_U;
    delete img_1_data_stream_0_U;
    delete img_1_data_stream_1_U;
    delete img_1_data_stream_2_U;
    delete img_1_rows_V_c22_U;
    delete img_1_cols_V_c23_U;
    delete start_for_Merge_U0_U;
    delete start_for_Split_U0_U;
    delete start_for_GaussiajbC_U;
    delete start_for_GaussiakbM_U;
    delete start_for_GaussialbW_U;
    delete start_for_Mat2AXImb6_U;
}

void ov5640_GaussianBlur::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void ov5640_GaussianBlur::thread_AXIvideo2Mat_U0_ap_continue() {
    AXIvideo2Mat_U0_ap_continue = ap_const_logic_1;
}

void ov5640_GaussianBlur::thread_AXIvideo2Mat_U0_ap_start() {
    AXIvideo2Mat_U0_ap_start = ap_const_logic_1;
}

void ov5640_GaussianBlur::thread_Block_proc_U0_ap_continue() {
    Block_proc_U0_ap_continue = ap_const_logic_1;
}

void ov5640_GaussianBlur::thread_Block_proc_U0_ap_start() {
    Block_proc_U0_ap_start = ap_const_logic_1;
}

void ov5640_GaussianBlur::thread_GaussianBlur162_U0_ap_continue() {
    GaussianBlur162_U0_ap_continue = ap_const_logic_1;
}

void ov5640_GaussianBlur::thread_GaussianBlur162_U0_ap_start() {
    GaussianBlur162_U0_ap_start = start_for_GaussianBlur162_U0_empty_n.read();
}

void ov5640_GaussianBlur::thread_GaussianBlur162_U0_start_full_n() {
    GaussianBlur162_U0_start_full_n = ap_const_logic_1;
}

void ov5640_GaussianBlur::thread_GaussianBlur162_U0_start_write() {
    GaussianBlur162_U0_start_write = ap_const_logic_0;
}

void ov5640_GaussianBlur::thread_GaussianBlur163_U0_ap_continue() {
    GaussianBlur163_U0_ap_continue = ap_const_logic_1;
}

void ov5640_GaussianBlur::thread_GaussianBlur163_U0_ap_start() {
    GaussianBlur163_U0_ap_start = start_for_GaussianBlur163_U0_empty_n.read();
}

void ov5640_GaussianBlur::thread_GaussianBlur163_U0_start_full_n() {
    GaussianBlur163_U0_start_full_n = ap_const_logic_1;
}

void ov5640_GaussianBlur::thread_GaussianBlur163_U0_start_write() {
    GaussianBlur163_U0_start_write = ap_const_logic_0;
}

void ov5640_GaussianBlur::thread_GaussianBlur_U0_ap_continue() {
    GaussianBlur_U0_ap_continue = ap_const_logic_1;
}

void ov5640_GaussianBlur::thread_GaussianBlur_U0_ap_start() {
    GaussianBlur_U0_ap_start = start_for_GaussianBlur_U0_empty_n.read();
}

void ov5640_GaussianBlur::thread_GaussianBlur_U0_start_full_n() {
    GaussianBlur_U0_start_full_n = ap_const_logic_1;
}

void ov5640_GaussianBlur::thread_GaussianBlur_U0_start_write() {
    GaussianBlur_U0_start_write = ap_const_logic_0;
}

void ov5640_GaussianBlur::thread_INPUT_STREAM_TREADY() {
    INPUT_STREAM_TREADY = AXIvideo2Mat_U0_INPUT_STREAM_TREADY.read();
}

void ov5640_GaussianBlur::thread_Mat2AXIvideo_U0_ap_continue() {
    Mat2AXIvideo_U0_ap_continue = ap_const_logic_1;
}

void ov5640_GaussianBlur::thread_Mat2AXIvideo_U0_ap_start() {
    Mat2AXIvideo_U0_ap_start = start_for_Mat2AXIvideo_U0_empty_n.read();
}

void ov5640_GaussianBlur::thread_Mat2AXIvideo_U0_start_full_n() {
    Mat2AXIvideo_U0_start_full_n = ap_const_logic_1;
}

void ov5640_GaussianBlur::thread_Mat2AXIvideo_U0_start_write() {
    Mat2AXIvideo_U0_start_write = ap_const_logic_0;
}

void ov5640_GaussianBlur::thread_Merge_U0_ap_continue() {
    Merge_U0_ap_continue = ap_const_logic_1;
}

void ov5640_GaussianBlur::thread_Merge_U0_ap_start() {
    Merge_U0_ap_start = start_for_Merge_U0_empty_n.read();
}

void ov5640_GaussianBlur::thread_OUTPUT_STREAM_TDATA() {
    OUTPUT_STREAM_TDATA = Mat2AXIvideo_U0_OUTPUT_STREAM_TDATA.read();
}

void ov5640_GaussianBlur::thread_OUTPUT_STREAM_TDEST() {
    OUTPUT_STREAM_TDEST = Mat2AXIvideo_U0_OUTPUT_STREAM_TDEST.read();
}

void ov5640_GaussianBlur::thread_OUTPUT_STREAM_TID() {
    OUTPUT_STREAM_TID = Mat2AXIvideo_U0_OUTPUT_STREAM_TID.read();
}

void ov5640_GaussianBlur::thread_OUTPUT_STREAM_TKEEP() {
    OUTPUT_STREAM_TKEEP = Mat2AXIvideo_U0_OUTPUT_STREAM_TKEEP.read();
}

void ov5640_GaussianBlur::thread_OUTPUT_STREAM_TLAST() {
    OUTPUT_STREAM_TLAST = Mat2AXIvideo_U0_OUTPUT_STREAM_TLAST.read();
}

void ov5640_GaussianBlur::thread_OUTPUT_STREAM_TSTRB() {
    OUTPUT_STREAM_TSTRB = Mat2AXIvideo_U0_OUTPUT_STREAM_TSTRB.read();
}

void ov5640_GaussianBlur::thread_OUTPUT_STREAM_TUSER() {
    OUTPUT_STREAM_TUSER = Mat2AXIvideo_U0_OUTPUT_STREAM_TUSER.read();
}

void ov5640_GaussianBlur::thread_OUTPUT_STREAM_TVALID() {
    OUTPUT_STREAM_TVALID = Mat2AXIvideo_U0_OUTPUT_STREAM_TVALID.read();
}

void ov5640_GaussianBlur::thread_Split_U0_ap_continue() {
    Split_U0_ap_continue = ap_const_logic_1;
}

void ov5640_GaussianBlur::thread_Split_U0_ap_start() {
    Split_U0_ap_start = start_for_Split_U0_empty_n.read();
}

void ov5640_GaussianBlur::thread_Split_U0_start_full_n() {
    Split_U0_start_full_n = (start_for_GaussianBlur162_U0_full_n.read() & start_for_GaussianBlur163_U0_full_n.read() & start_for_GaussianBlur_U0_full_n.read());
}

void ov5640_GaussianBlur::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void ov5640_GaussianBlur::thread_ap_sync_continue() {
    ap_sync_continue = ap_const_logic_0;
}

void ov5640_GaussianBlur::thread_start_for_GaussianBlur162_U0_din() {
    start_for_GaussianBlur162_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void ov5640_GaussianBlur::thread_start_for_GaussianBlur163_U0_din() {
    start_for_GaussianBlur163_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void ov5640_GaussianBlur::thread_start_for_GaussianBlur_U0_din() {
    start_for_GaussianBlur_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void ov5640_GaussianBlur::thread_start_for_Mat2AXIvideo_U0_din() {
    start_for_Mat2AXIvideo_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void ov5640_GaussianBlur::thread_start_for_Merge_U0_din() {
    start_for_Merge_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void ov5640_GaussianBlur::thread_start_for_Split_U0_din() {
    start_for_Split_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void ov5640_GaussianBlur::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"INPUT_STREAM_TDATA\" :  \"" << INPUT_STREAM_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"INPUT_STREAM_TKEEP\" :  \"" << INPUT_STREAM_TKEEP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"INPUT_STREAM_TSTRB\" :  \"" << INPUT_STREAM_TSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"INPUT_STREAM_TUSER\" :  \"" << INPUT_STREAM_TUSER.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"INPUT_STREAM_TLAST\" :  \"" << INPUT_STREAM_TLAST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"INPUT_STREAM_TID\" :  \"" << INPUT_STREAM_TID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"INPUT_STREAM_TDEST\" :  \"" << INPUT_STREAM_TDEST.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"OUTPUT_STREAM_TDATA\" :  \"" << OUTPUT_STREAM_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"OUTPUT_STREAM_TKEEP\" :  \"" << OUTPUT_STREAM_TKEEP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"OUTPUT_STREAM_TSTRB\" :  \"" << OUTPUT_STREAM_TSTRB.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"OUTPUT_STREAM_TUSER\" :  \"" << OUTPUT_STREAM_TUSER.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"OUTPUT_STREAM_TLAST\" :  \"" << OUTPUT_STREAM_TLAST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"OUTPUT_STREAM_TID\" :  \"" << OUTPUT_STREAM_TID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"OUTPUT_STREAM_TDEST\" :  \"" << OUTPUT_STREAM_TDEST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"INPUT_STREAM_TVALID\" :  \"" << INPUT_STREAM_TVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"INPUT_STREAM_TREADY\" :  \"" << INPUT_STREAM_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"OUTPUT_STREAM_TVALID\" :  \"" << OUTPUT_STREAM_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"OUTPUT_STREAM_TREADY\" :  \"" << OUTPUT_STREAM_TREADY.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

