-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ov5640_GaussianBlur is
port (
    INPUT_STREAM_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
    INPUT_STREAM_TKEEP : IN STD_LOGIC_VECTOR (2 downto 0);
    INPUT_STREAM_TSTRB : IN STD_LOGIC_VECTOR (2 downto 0);
    INPUT_STREAM_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    INPUT_STREAM_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    INPUT_STREAM_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    INPUT_STREAM_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    OUTPUT_STREAM_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
    OUTPUT_STREAM_TKEEP : OUT STD_LOGIC_VECTOR (2 downto 0);
    OUTPUT_STREAM_TSTRB : OUT STD_LOGIC_VECTOR (2 downto 0);
    OUTPUT_STREAM_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    OUTPUT_STREAM_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    OUTPUT_STREAM_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    OUTPUT_STREAM_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    INPUT_STREAM_TVALID : IN STD_LOGIC;
    INPUT_STREAM_TREADY : OUT STD_LOGIC;
    OUTPUT_STREAM_TVALID : OUT STD_LOGIC;
    OUTPUT_STREAM_TREADY : IN STD_LOGIC );
end;


architecture behav of ov5640_GaussianBlur is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "ov5640_GaussianBlur,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg400-2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=10.674000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=9,HLS_SYN_DSP=12,HLS_SYN_FF=2361,HLS_SYN_LUT=3265,HLS_VERSION=2018_3}";
    constant ap_const_lv24_0 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal ap_rst_n_inv : STD_LOGIC;
    signal Block_proc_U0_ap_start : STD_LOGIC;
    signal Block_proc_U0_ap_done : STD_LOGIC;
    signal Block_proc_U0_ap_continue : STD_LOGIC;
    signal Block_proc_U0_ap_idle : STD_LOGIC;
    signal Block_proc_U0_ap_ready : STD_LOGIC;
    signal Block_proc_U0_start_out : STD_LOGIC;
    signal Block_proc_U0_start_write : STD_LOGIC;
    signal Block_proc_U0_img_0_rows_V_out_din : STD_LOGIC_VECTOR (9 downto 0);
    signal Block_proc_U0_img_0_rows_V_out_write : STD_LOGIC;
    signal Block_proc_U0_img_0_cols_V_out_din : STD_LOGIC_VECTOR (10 downto 0);
    signal Block_proc_U0_img_0_cols_V_out_write : STD_LOGIC;
    signal Block_proc_U0_img_1_rows_V_out_din : STD_LOGIC_VECTOR (9 downto 0);
    signal Block_proc_U0_img_1_rows_V_out_write : STD_LOGIC;
    signal Block_proc_U0_img_1_cols_V_out_din : STD_LOGIC_VECTOR (10 downto 0);
    signal Block_proc_U0_img_1_cols_V_out_write : STD_LOGIC;
    signal AXIvideo2Mat_U0_ap_start : STD_LOGIC;
    signal AXIvideo2Mat_U0_ap_done : STD_LOGIC;
    signal AXIvideo2Mat_U0_ap_continue : STD_LOGIC;
    signal AXIvideo2Mat_U0_ap_idle : STD_LOGIC;
    signal AXIvideo2Mat_U0_ap_ready : STD_LOGIC;
    signal AXIvideo2Mat_U0_start_out : STD_LOGIC;
    signal AXIvideo2Mat_U0_start_write : STD_LOGIC;
    signal AXIvideo2Mat_U0_INPUT_STREAM_TREADY : STD_LOGIC;
    signal AXIvideo2Mat_U0_img_rows_V_read : STD_LOGIC;
    signal AXIvideo2Mat_U0_img_cols_V_read : STD_LOGIC;
    signal AXIvideo2Mat_U0_img_data_stream_0_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal AXIvideo2Mat_U0_img_data_stream_0_V_write : STD_LOGIC;
    signal AXIvideo2Mat_U0_img_data_stream_1_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal AXIvideo2Mat_U0_img_data_stream_1_V_write : STD_LOGIC;
    signal AXIvideo2Mat_U0_img_data_stream_2_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal AXIvideo2Mat_U0_img_data_stream_2_V_write : STD_LOGIC;
    signal AXIvideo2Mat_U0_img_rows_V_out_din : STD_LOGIC_VECTOR (9 downto 0);
    signal AXIvideo2Mat_U0_img_rows_V_out_write : STD_LOGIC;
    signal AXIvideo2Mat_U0_img_cols_V_out_din : STD_LOGIC_VECTOR (10 downto 0);
    signal AXIvideo2Mat_U0_img_cols_V_out_write : STD_LOGIC;
    signal Split_U0_ap_start : STD_LOGIC;
    signal Split_U0_start_full_n : STD_LOGIC;
    signal Split_U0_ap_done : STD_LOGIC;
    signal Split_U0_ap_continue : STD_LOGIC;
    signal Split_U0_ap_idle : STD_LOGIC;
    signal Split_U0_ap_ready : STD_LOGIC;
    signal Split_U0_start_out : STD_LOGIC;
    signal Split_U0_start_write : STD_LOGIC;
    signal Split_U0_src_rows_V_read : STD_LOGIC;
    signal Split_U0_src_cols_V_read : STD_LOGIC;
    signal Split_U0_src_data_stream_0_V_read : STD_LOGIC;
    signal Split_U0_src_data_stream_1_V_read : STD_LOGIC;
    signal Split_U0_src_data_stream_2_V_read : STD_LOGIC;
    signal Split_U0_dst0_data_stream_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal Split_U0_dst0_data_stream_V_write : STD_LOGIC;
    signal Split_U0_dst1_data_stream_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal Split_U0_dst1_data_stream_V_write : STD_LOGIC;
    signal Split_U0_dst2_data_stream_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal Split_U0_dst2_data_stream_V_write : STD_LOGIC;
    signal GaussianBlur162_U0_ap_start : STD_LOGIC;
    signal GaussianBlur162_U0_ap_done : STD_LOGIC;
    signal GaussianBlur162_U0_ap_continue : STD_LOGIC;
    signal GaussianBlur162_U0_ap_idle : STD_LOGIC;
    signal GaussianBlur162_U0_ap_ready : STD_LOGIC;
    signal GaussianBlur162_U0_p_src_data_stream_V_read : STD_LOGIC;
    signal GaussianBlur162_U0_p_dst_data_stream_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal GaussianBlur162_U0_p_dst_data_stream_V_write : STD_LOGIC;
    signal GaussianBlur163_U0_ap_start : STD_LOGIC;
    signal GaussianBlur163_U0_ap_done : STD_LOGIC;
    signal GaussianBlur163_U0_ap_continue : STD_LOGIC;
    signal GaussianBlur163_U0_ap_idle : STD_LOGIC;
    signal GaussianBlur163_U0_ap_ready : STD_LOGIC;
    signal GaussianBlur163_U0_p_src_data_stream_V_read : STD_LOGIC;
    signal GaussianBlur163_U0_p_dst_data_stream_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal GaussianBlur163_U0_p_dst_data_stream_V_write : STD_LOGIC;
    signal GaussianBlur_U0_ap_start : STD_LOGIC;
    signal GaussianBlur_U0_ap_done : STD_LOGIC;
    signal GaussianBlur_U0_ap_continue : STD_LOGIC;
    signal GaussianBlur_U0_ap_idle : STD_LOGIC;
    signal GaussianBlur_U0_ap_ready : STD_LOGIC;
    signal GaussianBlur_U0_p_src_data_stream_V_read : STD_LOGIC;
    signal GaussianBlur_U0_p_dst_data_stream_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal GaussianBlur_U0_p_dst_data_stream_V_write : STD_LOGIC;
    signal Merge_U0_ap_start : STD_LOGIC;
    signal Merge_U0_ap_done : STD_LOGIC;
    signal Merge_U0_ap_continue : STD_LOGIC;
    signal Merge_U0_ap_idle : STD_LOGIC;
    signal Merge_U0_ap_ready : STD_LOGIC;
    signal Merge_U0_start_out : STD_LOGIC;
    signal Merge_U0_start_write : STD_LOGIC;
    signal Merge_U0_src0_data_stream_V_read : STD_LOGIC;
    signal Merge_U0_src1_data_stream_V_read : STD_LOGIC;
    signal Merge_U0_src2_data_stream_V_read : STD_LOGIC;
    signal Merge_U0_dst_rows_V_read : STD_LOGIC;
    signal Merge_U0_dst_cols_V_read : STD_LOGIC;
    signal Merge_U0_dst_data_stream_0_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal Merge_U0_dst_data_stream_0_V_write : STD_LOGIC;
    signal Merge_U0_dst_data_stream_1_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal Merge_U0_dst_data_stream_1_V_write : STD_LOGIC;
    signal Merge_U0_dst_data_stream_2_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal Merge_U0_dst_data_stream_2_V_write : STD_LOGIC;
    signal Merge_U0_dst_rows_V_out_din : STD_LOGIC_VECTOR (9 downto 0);
    signal Merge_U0_dst_rows_V_out_write : STD_LOGIC;
    signal Merge_U0_dst_cols_V_out_din : STD_LOGIC_VECTOR (10 downto 0);
    signal Merge_U0_dst_cols_V_out_write : STD_LOGIC;
    signal Mat2AXIvideo_U0_ap_start : STD_LOGIC;
    signal Mat2AXIvideo_U0_ap_done : STD_LOGIC;
    signal Mat2AXIvideo_U0_ap_continue : STD_LOGIC;
    signal Mat2AXIvideo_U0_ap_idle : STD_LOGIC;
    signal Mat2AXIvideo_U0_ap_ready : STD_LOGIC;
    signal Mat2AXIvideo_U0_img_rows_V_read : STD_LOGIC;
    signal Mat2AXIvideo_U0_img_cols_V_read : STD_LOGIC;
    signal Mat2AXIvideo_U0_img_data_stream_0_V_read : STD_LOGIC;
    signal Mat2AXIvideo_U0_img_data_stream_1_V_read : STD_LOGIC;
    signal Mat2AXIvideo_U0_img_data_stream_2_V_read : STD_LOGIC;
    signal Mat2AXIvideo_U0_OUTPUT_STREAM_TDATA : STD_LOGIC_VECTOR (23 downto 0);
    signal Mat2AXIvideo_U0_OUTPUT_STREAM_TVALID : STD_LOGIC;
    signal Mat2AXIvideo_U0_OUTPUT_STREAM_TKEEP : STD_LOGIC_VECTOR (2 downto 0);
    signal Mat2AXIvideo_U0_OUTPUT_STREAM_TSTRB : STD_LOGIC_VECTOR (2 downto 0);
    signal Mat2AXIvideo_U0_OUTPUT_STREAM_TUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal Mat2AXIvideo_U0_OUTPUT_STREAM_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal Mat2AXIvideo_U0_OUTPUT_STREAM_TID : STD_LOGIC_VECTOR (0 downto 0);
    signal Mat2AXIvideo_U0_OUTPUT_STREAM_TDEST : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sync_continue : STD_LOGIC;
    signal img_0_rows_V_c_full_n : STD_LOGIC;
    signal img_0_rows_V_c_dout : STD_LOGIC_VECTOR (9 downto 0);
    signal img_0_rows_V_c_empty_n : STD_LOGIC;
    signal img_0_cols_V_c_full_n : STD_LOGIC;
    signal img_0_cols_V_c_dout : STD_LOGIC_VECTOR (10 downto 0);
    signal img_0_cols_V_c_empty_n : STD_LOGIC;
    signal img_1_rows_V_c_full_n : STD_LOGIC;
    signal img_1_rows_V_c_dout : STD_LOGIC_VECTOR (9 downto 0);
    signal img_1_rows_V_c_empty_n : STD_LOGIC;
    signal img_1_cols_V_c_full_n : STD_LOGIC;
    signal img_1_cols_V_c_dout : STD_LOGIC_VECTOR (10 downto 0);
    signal img_1_cols_V_c_empty_n : STD_LOGIC;
    signal img_0_data_stream_0_full_n : STD_LOGIC;
    signal img_0_data_stream_0_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal img_0_data_stream_0_empty_n : STD_LOGIC;
    signal img_0_data_stream_1_full_n : STD_LOGIC;
    signal img_0_data_stream_1_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal img_0_data_stream_1_empty_n : STD_LOGIC;
    signal img_0_data_stream_2_full_n : STD_LOGIC;
    signal img_0_data_stream_2_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal img_0_data_stream_2_empty_n : STD_LOGIC;
    signal img_0_rows_V_c20_full_n : STD_LOGIC;
    signal img_0_rows_V_c20_dout : STD_LOGIC_VECTOR (9 downto 0);
    signal img_0_rows_V_c20_empty_n : STD_LOGIC;
    signal img_0_cols_V_c21_full_n : STD_LOGIC;
    signal img_0_cols_V_c21_dout : STD_LOGIC_VECTOR (10 downto 0);
    signal img_0_cols_V_c21_empty_n : STD_LOGIC;
    signal img_B_data_stream_0_full_n : STD_LOGIC;
    signal img_B_data_stream_0_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal img_B_data_stream_0_empty_n : STD_LOGIC;
    signal img_G_data_stream_0_full_n : STD_LOGIC;
    signal img_G_data_stream_0_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal img_G_data_stream_0_empty_n : STD_LOGIC;
    signal img_R_data_stream_0_full_n : STD_LOGIC;
    signal img_R_data_stream_0_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal img_R_data_stream_0_empty_n : STD_LOGIC;
    signal img_B_f_data_stream_s_full_n : STD_LOGIC;
    signal img_B_f_data_stream_s_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal img_B_f_data_stream_s_empty_n : STD_LOGIC;
    signal img_G_f_data_stream_s_full_n : STD_LOGIC;
    signal img_G_f_data_stream_s_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal img_G_f_data_stream_s_empty_n : STD_LOGIC;
    signal img_R_f_data_stream_s_full_n : STD_LOGIC;
    signal img_R_f_data_stream_s_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal img_R_f_data_stream_s_empty_n : STD_LOGIC;
    signal img_1_data_stream_0_full_n : STD_LOGIC;
    signal img_1_data_stream_0_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal img_1_data_stream_0_empty_n : STD_LOGIC;
    signal img_1_data_stream_1_full_n : STD_LOGIC;
    signal img_1_data_stream_1_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal img_1_data_stream_1_empty_n : STD_LOGIC;
    signal img_1_data_stream_2_full_n : STD_LOGIC;
    signal img_1_data_stream_2_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal img_1_data_stream_2_empty_n : STD_LOGIC;
    signal img_1_rows_V_c22_full_n : STD_LOGIC;
    signal img_1_rows_V_c22_dout : STD_LOGIC_VECTOR (9 downto 0);
    signal img_1_rows_V_c22_empty_n : STD_LOGIC;
    signal img_1_cols_V_c23_full_n : STD_LOGIC;
    signal img_1_cols_V_c23_dout : STD_LOGIC_VECTOR (10 downto 0);
    signal img_1_cols_V_c23_empty_n : STD_LOGIC;
    signal start_for_Merge_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_Merge_U0_full_n : STD_LOGIC;
    signal start_for_Merge_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_Merge_U0_empty_n : STD_LOGIC;
    signal start_for_Split_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_Split_U0_full_n : STD_LOGIC;
    signal start_for_Split_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_Split_U0_empty_n : STD_LOGIC;
    signal start_for_GaussianBlur162_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_GaussianBlur162_U0_full_n : STD_LOGIC;
    signal start_for_GaussianBlur162_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_GaussianBlur162_U0_empty_n : STD_LOGIC;
    signal start_for_GaussianBlur163_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_GaussianBlur163_U0_full_n : STD_LOGIC;
    signal start_for_GaussianBlur163_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_GaussianBlur163_U0_empty_n : STD_LOGIC;
    signal start_for_GaussianBlur_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_GaussianBlur_U0_full_n : STD_LOGIC;
    signal start_for_GaussianBlur_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_GaussianBlur_U0_empty_n : STD_LOGIC;
    signal GaussianBlur162_U0_start_full_n : STD_LOGIC;
    signal GaussianBlur162_U0_start_write : STD_LOGIC;
    signal GaussianBlur163_U0_start_full_n : STD_LOGIC;
    signal GaussianBlur163_U0_start_write : STD_LOGIC;
    signal GaussianBlur_U0_start_full_n : STD_LOGIC;
    signal GaussianBlur_U0_start_write : STD_LOGIC;
    signal start_for_Mat2AXIvideo_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_Mat2AXIvideo_U0_full_n : STD_LOGIC;
    signal start_for_Mat2AXIvideo_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_Mat2AXIvideo_U0_empty_n : STD_LOGIC;
    signal Mat2AXIvideo_U0_start_full_n : STD_LOGIC;
    signal Mat2AXIvideo_U0_start_write : STD_LOGIC;

    component Block_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        img_0_rows_V_out_din : OUT STD_LOGIC_VECTOR (9 downto 0);
        img_0_rows_V_out_full_n : IN STD_LOGIC;
        img_0_rows_V_out_write : OUT STD_LOGIC;
        img_0_cols_V_out_din : OUT STD_LOGIC_VECTOR (10 downto 0);
        img_0_cols_V_out_full_n : IN STD_LOGIC;
        img_0_cols_V_out_write : OUT STD_LOGIC;
        img_1_rows_V_out_din : OUT STD_LOGIC_VECTOR (9 downto 0);
        img_1_rows_V_out_full_n : IN STD_LOGIC;
        img_1_rows_V_out_write : OUT STD_LOGIC;
        img_1_cols_V_out_din : OUT STD_LOGIC_VECTOR (10 downto 0);
        img_1_cols_V_out_full_n : IN STD_LOGIC;
        img_1_cols_V_out_write : OUT STD_LOGIC );
    end component;


    component AXIvideo2Mat IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        INPUT_STREAM_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
        INPUT_STREAM_TVALID : IN STD_LOGIC;
        INPUT_STREAM_TREADY : OUT STD_LOGIC;
        INPUT_STREAM_TKEEP : IN STD_LOGIC_VECTOR (2 downto 0);
        INPUT_STREAM_TSTRB : IN STD_LOGIC_VECTOR (2 downto 0);
        INPUT_STREAM_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        INPUT_STREAM_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        INPUT_STREAM_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        INPUT_STREAM_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
        img_rows_V_dout : IN STD_LOGIC_VECTOR (9 downto 0);
        img_rows_V_empty_n : IN STD_LOGIC;
        img_rows_V_read : OUT STD_LOGIC;
        img_cols_V_dout : IN STD_LOGIC_VECTOR (10 downto 0);
        img_cols_V_empty_n : IN STD_LOGIC;
        img_cols_V_read : OUT STD_LOGIC;
        img_data_stream_0_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        img_data_stream_0_V_full_n : IN STD_LOGIC;
        img_data_stream_0_V_write : OUT STD_LOGIC;
        img_data_stream_1_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        img_data_stream_1_V_full_n : IN STD_LOGIC;
        img_data_stream_1_V_write : OUT STD_LOGIC;
        img_data_stream_2_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        img_data_stream_2_V_full_n : IN STD_LOGIC;
        img_data_stream_2_V_write : OUT STD_LOGIC;
        img_rows_V_out_din : OUT STD_LOGIC_VECTOR (9 downto 0);
        img_rows_V_out_full_n : IN STD_LOGIC;
        img_rows_V_out_write : OUT STD_LOGIC;
        img_cols_V_out_din : OUT STD_LOGIC_VECTOR (10 downto 0);
        img_cols_V_out_full_n : IN STD_LOGIC;
        img_cols_V_out_write : OUT STD_LOGIC );
    end component;


    component Split IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        src_rows_V_dout : IN STD_LOGIC_VECTOR (9 downto 0);
        src_rows_V_empty_n : IN STD_LOGIC;
        src_rows_V_read : OUT STD_LOGIC;
        src_cols_V_dout : IN STD_LOGIC_VECTOR (10 downto 0);
        src_cols_V_empty_n : IN STD_LOGIC;
        src_cols_V_read : OUT STD_LOGIC;
        src_data_stream_0_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        src_data_stream_0_V_empty_n : IN STD_LOGIC;
        src_data_stream_0_V_read : OUT STD_LOGIC;
        src_data_stream_1_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        src_data_stream_1_V_empty_n : IN STD_LOGIC;
        src_data_stream_1_V_read : OUT STD_LOGIC;
        src_data_stream_2_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        src_data_stream_2_V_empty_n : IN STD_LOGIC;
        src_data_stream_2_V_read : OUT STD_LOGIC;
        dst0_data_stream_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        dst0_data_stream_V_full_n : IN STD_LOGIC;
        dst0_data_stream_V_write : OUT STD_LOGIC;
        dst1_data_stream_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        dst1_data_stream_V_full_n : IN STD_LOGIC;
        dst1_data_stream_V_write : OUT STD_LOGIC;
        dst2_data_stream_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        dst2_data_stream_V_full_n : IN STD_LOGIC;
        dst2_data_stream_V_write : OUT STD_LOGIC );
    end component;


    component GaussianBlur162 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        p_src_data_stream_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        p_src_data_stream_V_empty_n : IN STD_LOGIC;
        p_src_data_stream_V_read : OUT STD_LOGIC;
        p_dst_data_stream_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_dst_data_stream_V_full_n : IN STD_LOGIC;
        p_dst_data_stream_V_write : OUT STD_LOGIC );
    end component;


    component GaussianBlur163 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        p_src_data_stream_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        p_src_data_stream_V_empty_n : IN STD_LOGIC;
        p_src_data_stream_V_read : OUT STD_LOGIC;
        p_dst_data_stream_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_dst_data_stream_V_full_n : IN STD_LOGIC;
        p_dst_data_stream_V_write : OUT STD_LOGIC );
    end component;


    component GaussianBlur IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        p_src_data_stream_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        p_src_data_stream_V_empty_n : IN STD_LOGIC;
        p_src_data_stream_V_read : OUT STD_LOGIC;
        p_dst_data_stream_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_dst_data_stream_V_full_n : IN STD_LOGIC;
        p_dst_data_stream_V_write : OUT STD_LOGIC );
    end component;


    component Merge IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        src0_data_stream_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        src0_data_stream_V_empty_n : IN STD_LOGIC;
        src0_data_stream_V_read : OUT STD_LOGIC;
        src1_data_stream_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        src1_data_stream_V_empty_n : IN STD_LOGIC;
        src1_data_stream_V_read : OUT STD_LOGIC;
        src2_data_stream_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        src2_data_stream_V_empty_n : IN STD_LOGIC;
        src2_data_stream_V_read : OUT STD_LOGIC;
        dst_rows_V_dout : IN STD_LOGIC_VECTOR (9 downto 0);
        dst_rows_V_empty_n : IN STD_LOGIC;
        dst_rows_V_read : OUT STD_LOGIC;
        dst_cols_V_dout : IN STD_LOGIC_VECTOR (10 downto 0);
        dst_cols_V_empty_n : IN STD_LOGIC;
        dst_cols_V_read : OUT STD_LOGIC;
        dst_data_stream_0_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        dst_data_stream_0_V_full_n : IN STD_LOGIC;
        dst_data_stream_0_V_write : OUT STD_LOGIC;
        dst_data_stream_1_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        dst_data_stream_1_V_full_n : IN STD_LOGIC;
        dst_data_stream_1_V_write : OUT STD_LOGIC;
        dst_data_stream_2_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        dst_data_stream_2_V_full_n : IN STD_LOGIC;
        dst_data_stream_2_V_write : OUT STD_LOGIC;
        dst_rows_V_out_din : OUT STD_LOGIC_VECTOR (9 downto 0);
        dst_rows_V_out_full_n : IN STD_LOGIC;
        dst_rows_V_out_write : OUT STD_LOGIC;
        dst_cols_V_out_din : OUT STD_LOGIC_VECTOR (10 downto 0);
        dst_cols_V_out_full_n : IN STD_LOGIC;
        dst_cols_V_out_write : OUT STD_LOGIC );
    end component;


    component Mat2AXIvideo IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        img_rows_V_dout : IN STD_LOGIC_VECTOR (9 downto 0);
        img_rows_V_empty_n : IN STD_LOGIC;
        img_rows_V_read : OUT STD_LOGIC;
        img_cols_V_dout : IN STD_LOGIC_VECTOR (10 downto 0);
        img_cols_V_empty_n : IN STD_LOGIC;
        img_cols_V_read : OUT STD_LOGIC;
        img_data_stream_0_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        img_data_stream_0_V_empty_n : IN STD_LOGIC;
        img_data_stream_0_V_read : OUT STD_LOGIC;
        img_data_stream_1_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        img_data_stream_1_V_empty_n : IN STD_LOGIC;
        img_data_stream_1_V_read : OUT STD_LOGIC;
        img_data_stream_2_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        img_data_stream_2_V_empty_n : IN STD_LOGIC;
        img_data_stream_2_V_read : OUT STD_LOGIC;
        OUTPUT_STREAM_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
        OUTPUT_STREAM_TVALID : OUT STD_LOGIC;
        OUTPUT_STREAM_TREADY : IN STD_LOGIC;
        OUTPUT_STREAM_TKEEP : OUT STD_LOGIC_VECTOR (2 downto 0);
        OUTPUT_STREAM_TSTRB : OUT STD_LOGIC_VECTOR (2 downto 0);
        OUTPUT_STREAM_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        OUTPUT_STREAM_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        OUTPUT_STREAM_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
        OUTPUT_STREAM_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component fifo_w10_d2_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (9 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (9 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component fifo_w11_d2_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (10 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (10 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component fifo_w10_d5_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (9 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (9 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component fifo_w11_d5_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (10 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (10 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component fifo_w8_d2_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (7 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component start_for_Merge_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component start_for_Split_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component start_for_GaussiajbC IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component start_for_GaussiakbM IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component start_for_GaussialbW IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component start_for_Mat2AXImb6 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    Block_proc_U0 : component Block_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => Block_proc_U0_ap_start,
        start_full_n => start_for_Merge_U0_full_n,
        ap_done => Block_proc_U0_ap_done,
        ap_continue => Block_proc_U0_ap_continue,
        ap_idle => Block_proc_U0_ap_idle,
        ap_ready => Block_proc_U0_ap_ready,
        start_out => Block_proc_U0_start_out,
        start_write => Block_proc_U0_start_write,
        img_0_rows_V_out_din => Block_proc_U0_img_0_rows_V_out_din,
        img_0_rows_V_out_full_n => img_0_rows_V_c_full_n,
        img_0_rows_V_out_write => Block_proc_U0_img_0_rows_V_out_write,
        img_0_cols_V_out_din => Block_proc_U0_img_0_cols_V_out_din,
        img_0_cols_V_out_full_n => img_0_cols_V_c_full_n,
        img_0_cols_V_out_write => Block_proc_U0_img_0_cols_V_out_write,
        img_1_rows_V_out_din => Block_proc_U0_img_1_rows_V_out_din,
        img_1_rows_V_out_full_n => img_1_rows_V_c_full_n,
        img_1_rows_V_out_write => Block_proc_U0_img_1_rows_V_out_write,
        img_1_cols_V_out_din => Block_proc_U0_img_1_cols_V_out_din,
        img_1_cols_V_out_full_n => img_1_cols_V_c_full_n,
        img_1_cols_V_out_write => Block_proc_U0_img_1_cols_V_out_write);

    AXIvideo2Mat_U0 : component AXIvideo2Mat
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => AXIvideo2Mat_U0_ap_start,
        start_full_n => start_for_Split_U0_full_n,
        ap_done => AXIvideo2Mat_U0_ap_done,
        ap_continue => AXIvideo2Mat_U0_ap_continue,
        ap_idle => AXIvideo2Mat_U0_ap_idle,
        ap_ready => AXIvideo2Mat_U0_ap_ready,
        start_out => AXIvideo2Mat_U0_start_out,
        start_write => AXIvideo2Mat_U0_start_write,
        INPUT_STREAM_TDATA => INPUT_STREAM_TDATA,
        INPUT_STREAM_TVALID => INPUT_STREAM_TVALID,
        INPUT_STREAM_TREADY => AXIvideo2Mat_U0_INPUT_STREAM_TREADY,
        INPUT_STREAM_TKEEP => INPUT_STREAM_TKEEP,
        INPUT_STREAM_TSTRB => INPUT_STREAM_TSTRB,
        INPUT_STREAM_TUSER => INPUT_STREAM_TUSER,
        INPUT_STREAM_TLAST => INPUT_STREAM_TLAST,
        INPUT_STREAM_TID => INPUT_STREAM_TID,
        INPUT_STREAM_TDEST => INPUT_STREAM_TDEST,
        img_rows_V_dout => img_0_rows_V_c_dout,
        img_rows_V_empty_n => img_0_rows_V_c_empty_n,
        img_rows_V_read => AXIvideo2Mat_U0_img_rows_V_read,
        img_cols_V_dout => img_0_cols_V_c_dout,
        img_cols_V_empty_n => img_0_cols_V_c_empty_n,
        img_cols_V_read => AXIvideo2Mat_U0_img_cols_V_read,
        img_data_stream_0_V_din => AXIvideo2Mat_U0_img_data_stream_0_V_din,
        img_data_stream_0_V_full_n => img_0_data_stream_0_full_n,
        img_data_stream_0_V_write => AXIvideo2Mat_U0_img_data_stream_0_V_write,
        img_data_stream_1_V_din => AXIvideo2Mat_U0_img_data_stream_1_V_din,
        img_data_stream_1_V_full_n => img_0_data_stream_1_full_n,
        img_data_stream_1_V_write => AXIvideo2Mat_U0_img_data_stream_1_V_write,
        img_data_stream_2_V_din => AXIvideo2Mat_U0_img_data_stream_2_V_din,
        img_data_stream_2_V_full_n => img_0_data_stream_2_full_n,
        img_data_stream_2_V_write => AXIvideo2Mat_U0_img_data_stream_2_V_write,
        img_rows_V_out_din => AXIvideo2Mat_U0_img_rows_V_out_din,
        img_rows_V_out_full_n => img_0_rows_V_c20_full_n,
        img_rows_V_out_write => AXIvideo2Mat_U0_img_rows_V_out_write,
        img_cols_V_out_din => AXIvideo2Mat_U0_img_cols_V_out_din,
        img_cols_V_out_full_n => img_0_cols_V_c21_full_n,
        img_cols_V_out_write => AXIvideo2Mat_U0_img_cols_V_out_write);

    Split_U0 : component Split
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => Split_U0_ap_start,
        start_full_n => Split_U0_start_full_n,
        ap_done => Split_U0_ap_done,
        ap_continue => Split_U0_ap_continue,
        ap_idle => Split_U0_ap_idle,
        ap_ready => Split_U0_ap_ready,
        start_out => Split_U0_start_out,
        start_write => Split_U0_start_write,
        src_rows_V_dout => img_0_rows_V_c20_dout,
        src_rows_V_empty_n => img_0_rows_V_c20_empty_n,
        src_rows_V_read => Split_U0_src_rows_V_read,
        src_cols_V_dout => img_0_cols_V_c21_dout,
        src_cols_V_empty_n => img_0_cols_V_c21_empty_n,
        src_cols_V_read => Split_U0_src_cols_V_read,
        src_data_stream_0_V_dout => img_0_data_stream_0_dout,
        src_data_stream_0_V_empty_n => img_0_data_stream_0_empty_n,
        src_data_stream_0_V_read => Split_U0_src_data_stream_0_V_read,
        src_data_stream_1_V_dout => img_0_data_stream_1_dout,
        src_data_stream_1_V_empty_n => img_0_data_stream_1_empty_n,
        src_data_stream_1_V_read => Split_U0_src_data_stream_1_V_read,
        src_data_stream_2_V_dout => img_0_data_stream_2_dout,
        src_data_stream_2_V_empty_n => img_0_data_stream_2_empty_n,
        src_data_stream_2_V_read => Split_U0_src_data_stream_2_V_read,
        dst0_data_stream_V_din => Split_U0_dst0_data_stream_V_din,
        dst0_data_stream_V_full_n => img_B_data_stream_0_full_n,
        dst0_data_stream_V_write => Split_U0_dst0_data_stream_V_write,
        dst1_data_stream_V_din => Split_U0_dst1_data_stream_V_din,
        dst1_data_stream_V_full_n => img_G_data_stream_0_full_n,
        dst1_data_stream_V_write => Split_U0_dst1_data_stream_V_write,
        dst2_data_stream_V_din => Split_U0_dst2_data_stream_V_din,
        dst2_data_stream_V_full_n => img_R_data_stream_0_full_n,
        dst2_data_stream_V_write => Split_U0_dst2_data_stream_V_write);

    GaussianBlur162_U0 : component GaussianBlur162
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => GaussianBlur162_U0_ap_start,
        ap_done => GaussianBlur162_U0_ap_done,
        ap_continue => GaussianBlur162_U0_ap_continue,
        ap_idle => GaussianBlur162_U0_ap_idle,
        ap_ready => GaussianBlur162_U0_ap_ready,
        p_src_data_stream_V_dout => img_B_data_stream_0_dout,
        p_src_data_stream_V_empty_n => img_B_data_stream_0_empty_n,
        p_src_data_stream_V_read => GaussianBlur162_U0_p_src_data_stream_V_read,
        p_dst_data_stream_V_din => GaussianBlur162_U0_p_dst_data_stream_V_din,
        p_dst_data_stream_V_full_n => img_B_f_data_stream_s_full_n,
        p_dst_data_stream_V_write => GaussianBlur162_U0_p_dst_data_stream_V_write);

    GaussianBlur163_U0 : component GaussianBlur163
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => GaussianBlur163_U0_ap_start,
        ap_done => GaussianBlur163_U0_ap_done,
        ap_continue => GaussianBlur163_U0_ap_continue,
        ap_idle => GaussianBlur163_U0_ap_idle,
        ap_ready => GaussianBlur163_U0_ap_ready,
        p_src_data_stream_V_dout => img_G_data_stream_0_dout,
        p_src_data_stream_V_empty_n => img_G_data_stream_0_empty_n,
        p_src_data_stream_V_read => GaussianBlur163_U0_p_src_data_stream_V_read,
        p_dst_data_stream_V_din => GaussianBlur163_U0_p_dst_data_stream_V_din,
        p_dst_data_stream_V_full_n => img_G_f_data_stream_s_full_n,
        p_dst_data_stream_V_write => GaussianBlur163_U0_p_dst_data_stream_V_write);

    GaussianBlur_U0 : component GaussianBlur
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => GaussianBlur_U0_ap_start,
        ap_done => GaussianBlur_U0_ap_done,
        ap_continue => GaussianBlur_U0_ap_continue,
        ap_idle => GaussianBlur_U0_ap_idle,
        ap_ready => GaussianBlur_U0_ap_ready,
        p_src_data_stream_V_dout => img_R_data_stream_0_dout,
        p_src_data_stream_V_empty_n => img_R_data_stream_0_empty_n,
        p_src_data_stream_V_read => GaussianBlur_U0_p_src_data_stream_V_read,
        p_dst_data_stream_V_din => GaussianBlur_U0_p_dst_data_stream_V_din,
        p_dst_data_stream_V_full_n => img_R_f_data_stream_s_full_n,
        p_dst_data_stream_V_write => GaussianBlur_U0_p_dst_data_stream_V_write);

    Merge_U0 : component Merge
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => Merge_U0_ap_start,
        start_full_n => start_for_Mat2AXIvideo_U0_full_n,
        ap_done => Merge_U0_ap_done,
        ap_continue => Merge_U0_ap_continue,
        ap_idle => Merge_U0_ap_idle,
        ap_ready => Merge_U0_ap_ready,
        start_out => Merge_U0_start_out,
        start_write => Merge_U0_start_write,
        src0_data_stream_V_dout => img_B_f_data_stream_s_dout,
        src0_data_stream_V_empty_n => img_B_f_data_stream_s_empty_n,
        src0_data_stream_V_read => Merge_U0_src0_data_stream_V_read,
        src1_data_stream_V_dout => img_G_f_data_stream_s_dout,
        src1_data_stream_V_empty_n => img_G_f_data_stream_s_empty_n,
        src1_data_stream_V_read => Merge_U0_src1_data_stream_V_read,
        src2_data_stream_V_dout => img_R_f_data_stream_s_dout,
        src2_data_stream_V_empty_n => img_R_f_data_stream_s_empty_n,
        src2_data_stream_V_read => Merge_U0_src2_data_stream_V_read,
        dst_rows_V_dout => img_1_rows_V_c_dout,
        dst_rows_V_empty_n => img_1_rows_V_c_empty_n,
        dst_rows_V_read => Merge_U0_dst_rows_V_read,
        dst_cols_V_dout => img_1_cols_V_c_dout,
        dst_cols_V_empty_n => img_1_cols_V_c_empty_n,
        dst_cols_V_read => Merge_U0_dst_cols_V_read,
        dst_data_stream_0_V_din => Merge_U0_dst_data_stream_0_V_din,
        dst_data_stream_0_V_full_n => img_1_data_stream_0_full_n,
        dst_data_stream_0_V_write => Merge_U0_dst_data_stream_0_V_write,
        dst_data_stream_1_V_din => Merge_U0_dst_data_stream_1_V_din,
        dst_data_stream_1_V_full_n => img_1_data_stream_1_full_n,
        dst_data_stream_1_V_write => Merge_U0_dst_data_stream_1_V_write,
        dst_data_stream_2_V_din => Merge_U0_dst_data_stream_2_V_din,
        dst_data_stream_2_V_full_n => img_1_data_stream_2_full_n,
        dst_data_stream_2_V_write => Merge_U0_dst_data_stream_2_V_write,
        dst_rows_V_out_din => Merge_U0_dst_rows_V_out_din,
        dst_rows_V_out_full_n => img_1_rows_V_c22_full_n,
        dst_rows_V_out_write => Merge_U0_dst_rows_V_out_write,
        dst_cols_V_out_din => Merge_U0_dst_cols_V_out_din,
        dst_cols_V_out_full_n => img_1_cols_V_c23_full_n,
        dst_cols_V_out_write => Merge_U0_dst_cols_V_out_write);

    Mat2AXIvideo_U0 : component Mat2AXIvideo
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => Mat2AXIvideo_U0_ap_start,
        ap_done => Mat2AXIvideo_U0_ap_done,
        ap_continue => Mat2AXIvideo_U0_ap_continue,
        ap_idle => Mat2AXIvideo_U0_ap_idle,
        ap_ready => Mat2AXIvideo_U0_ap_ready,
        img_rows_V_dout => img_1_rows_V_c22_dout,
        img_rows_V_empty_n => img_1_rows_V_c22_empty_n,
        img_rows_V_read => Mat2AXIvideo_U0_img_rows_V_read,
        img_cols_V_dout => img_1_cols_V_c23_dout,
        img_cols_V_empty_n => img_1_cols_V_c23_empty_n,
        img_cols_V_read => Mat2AXIvideo_U0_img_cols_V_read,
        img_data_stream_0_V_dout => img_1_data_stream_0_dout,
        img_data_stream_0_V_empty_n => img_1_data_stream_0_empty_n,
        img_data_stream_0_V_read => Mat2AXIvideo_U0_img_data_stream_0_V_read,
        img_data_stream_1_V_dout => img_1_data_stream_1_dout,
        img_data_stream_1_V_empty_n => img_1_data_stream_1_empty_n,
        img_data_stream_1_V_read => Mat2AXIvideo_U0_img_data_stream_1_V_read,
        img_data_stream_2_V_dout => img_1_data_stream_2_dout,
        img_data_stream_2_V_empty_n => img_1_data_stream_2_empty_n,
        img_data_stream_2_V_read => Mat2AXIvideo_U0_img_data_stream_2_V_read,
        OUTPUT_STREAM_TDATA => Mat2AXIvideo_U0_OUTPUT_STREAM_TDATA,
        OUTPUT_STREAM_TVALID => Mat2AXIvideo_U0_OUTPUT_STREAM_TVALID,
        OUTPUT_STREAM_TREADY => OUTPUT_STREAM_TREADY,
        OUTPUT_STREAM_TKEEP => Mat2AXIvideo_U0_OUTPUT_STREAM_TKEEP,
        OUTPUT_STREAM_TSTRB => Mat2AXIvideo_U0_OUTPUT_STREAM_TSTRB,
        OUTPUT_STREAM_TUSER => Mat2AXIvideo_U0_OUTPUT_STREAM_TUSER,
        OUTPUT_STREAM_TLAST => Mat2AXIvideo_U0_OUTPUT_STREAM_TLAST,
        OUTPUT_STREAM_TID => Mat2AXIvideo_U0_OUTPUT_STREAM_TID,
        OUTPUT_STREAM_TDEST => Mat2AXIvideo_U0_OUTPUT_STREAM_TDEST);

    img_0_rows_V_c_U : component fifo_w10_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Block_proc_U0_img_0_rows_V_out_din,
        if_full_n => img_0_rows_V_c_full_n,
        if_write => Block_proc_U0_img_0_rows_V_out_write,
        if_dout => img_0_rows_V_c_dout,
        if_empty_n => img_0_rows_V_c_empty_n,
        if_read => AXIvideo2Mat_U0_img_rows_V_read);

    img_0_cols_V_c_U : component fifo_w11_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Block_proc_U0_img_0_cols_V_out_din,
        if_full_n => img_0_cols_V_c_full_n,
        if_write => Block_proc_U0_img_0_cols_V_out_write,
        if_dout => img_0_cols_V_c_dout,
        if_empty_n => img_0_cols_V_c_empty_n,
        if_read => AXIvideo2Mat_U0_img_cols_V_read);

    img_1_rows_V_c_U : component fifo_w10_d5_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Block_proc_U0_img_1_rows_V_out_din,
        if_full_n => img_1_rows_V_c_full_n,
        if_write => Block_proc_U0_img_1_rows_V_out_write,
        if_dout => img_1_rows_V_c_dout,
        if_empty_n => img_1_rows_V_c_empty_n,
        if_read => Merge_U0_dst_rows_V_read);

    img_1_cols_V_c_U : component fifo_w11_d5_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Block_proc_U0_img_1_cols_V_out_din,
        if_full_n => img_1_cols_V_c_full_n,
        if_write => Block_proc_U0_img_1_cols_V_out_write,
        if_dout => img_1_cols_V_c_dout,
        if_empty_n => img_1_cols_V_c_empty_n,
        if_read => Merge_U0_dst_cols_V_read);

    img_0_data_stream_0_U : component fifo_w8_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => AXIvideo2Mat_U0_img_data_stream_0_V_din,
        if_full_n => img_0_data_stream_0_full_n,
        if_write => AXIvideo2Mat_U0_img_data_stream_0_V_write,
        if_dout => img_0_data_stream_0_dout,
        if_empty_n => img_0_data_stream_0_empty_n,
        if_read => Split_U0_src_data_stream_0_V_read);

    img_0_data_stream_1_U : component fifo_w8_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => AXIvideo2Mat_U0_img_data_stream_1_V_din,
        if_full_n => img_0_data_stream_1_full_n,
        if_write => AXIvideo2Mat_U0_img_data_stream_1_V_write,
        if_dout => img_0_data_stream_1_dout,
        if_empty_n => img_0_data_stream_1_empty_n,
        if_read => Split_U0_src_data_stream_1_V_read);

    img_0_data_stream_2_U : component fifo_w8_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => AXIvideo2Mat_U0_img_data_stream_2_V_din,
        if_full_n => img_0_data_stream_2_full_n,
        if_write => AXIvideo2Mat_U0_img_data_stream_2_V_write,
        if_dout => img_0_data_stream_2_dout,
        if_empty_n => img_0_data_stream_2_empty_n,
        if_read => Split_U0_src_data_stream_2_V_read);

    img_0_rows_V_c20_U : component fifo_w10_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => AXIvideo2Mat_U0_img_rows_V_out_din,
        if_full_n => img_0_rows_V_c20_full_n,
        if_write => AXIvideo2Mat_U0_img_rows_V_out_write,
        if_dout => img_0_rows_V_c20_dout,
        if_empty_n => img_0_rows_V_c20_empty_n,
        if_read => Split_U0_src_rows_V_read);

    img_0_cols_V_c21_U : component fifo_w11_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => AXIvideo2Mat_U0_img_cols_V_out_din,
        if_full_n => img_0_cols_V_c21_full_n,
        if_write => AXIvideo2Mat_U0_img_cols_V_out_write,
        if_dout => img_0_cols_V_c21_dout,
        if_empty_n => img_0_cols_V_c21_empty_n,
        if_read => Split_U0_src_cols_V_read);

    img_B_data_stream_0_U : component fifo_w8_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Split_U0_dst0_data_stream_V_din,
        if_full_n => img_B_data_stream_0_full_n,
        if_write => Split_U0_dst0_data_stream_V_write,
        if_dout => img_B_data_stream_0_dout,
        if_empty_n => img_B_data_stream_0_empty_n,
        if_read => GaussianBlur162_U0_p_src_data_stream_V_read);

    img_G_data_stream_0_U : component fifo_w8_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Split_U0_dst1_data_stream_V_din,
        if_full_n => img_G_data_stream_0_full_n,
        if_write => Split_U0_dst1_data_stream_V_write,
        if_dout => img_G_data_stream_0_dout,
        if_empty_n => img_G_data_stream_0_empty_n,
        if_read => GaussianBlur163_U0_p_src_data_stream_V_read);

    img_R_data_stream_0_U : component fifo_w8_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Split_U0_dst2_data_stream_V_din,
        if_full_n => img_R_data_stream_0_full_n,
        if_write => Split_U0_dst2_data_stream_V_write,
        if_dout => img_R_data_stream_0_dout,
        if_empty_n => img_R_data_stream_0_empty_n,
        if_read => GaussianBlur_U0_p_src_data_stream_V_read);

    img_B_f_data_stream_s_U : component fifo_w8_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => GaussianBlur162_U0_p_dst_data_stream_V_din,
        if_full_n => img_B_f_data_stream_s_full_n,
        if_write => GaussianBlur162_U0_p_dst_data_stream_V_write,
        if_dout => img_B_f_data_stream_s_dout,
        if_empty_n => img_B_f_data_stream_s_empty_n,
        if_read => Merge_U0_src0_data_stream_V_read);

    img_G_f_data_stream_s_U : component fifo_w8_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => GaussianBlur163_U0_p_dst_data_stream_V_din,
        if_full_n => img_G_f_data_stream_s_full_n,
        if_write => GaussianBlur163_U0_p_dst_data_stream_V_write,
        if_dout => img_G_f_data_stream_s_dout,
        if_empty_n => img_G_f_data_stream_s_empty_n,
        if_read => Merge_U0_src1_data_stream_V_read);

    img_R_f_data_stream_s_U : component fifo_w8_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => GaussianBlur_U0_p_dst_data_stream_V_din,
        if_full_n => img_R_f_data_stream_s_full_n,
        if_write => GaussianBlur_U0_p_dst_data_stream_V_write,
        if_dout => img_R_f_data_stream_s_dout,
        if_empty_n => img_R_f_data_stream_s_empty_n,
        if_read => Merge_U0_src2_data_stream_V_read);

    img_1_data_stream_0_U : component fifo_w8_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Merge_U0_dst_data_stream_0_V_din,
        if_full_n => img_1_data_stream_0_full_n,
        if_write => Merge_U0_dst_data_stream_0_V_write,
        if_dout => img_1_data_stream_0_dout,
        if_empty_n => img_1_data_stream_0_empty_n,
        if_read => Mat2AXIvideo_U0_img_data_stream_0_V_read);

    img_1_data_stream_1_U : component fifo_w8_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Merge_U0_dst_data_stream_1_V_din,
        if_full_n => img_1_data_stream_1_full_n,
        if_write => Merge_U0_dst_data_stream_1_V_write,
        if_dout => img_1_data_stream_1_dout,
        if_empty_n => img_1_data_stream_1_empty_n,
        if_read => Mat2AXIvideo_U0_img_data_stream_1_V_read);

    img_1_data_stream_2_U : component fifo_w8_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Merge_U0_dst_data_stream_2_V_din,
        if_full_n => img_1_data_stream_2_full_n,
        if_write => Merge_U0_dst_data_stream_2_V_write,
        if_dout => img_1_data_stream_2_dout,
        if_empty_n => img_1_data_stream_2_empty_n,
        if_read => Mat2AXIvideo_U0_img_data_stream_2_V_read);

    img_1_rows_V_c22_U : component fifo_w10_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Merge_U0_dst_rows_V_out_din,
        if_full_n => img_1_rows_V_c22_full_n,
        if_write => Merge_U0_dst_rows_V_out_write,
        if_dout => img_1_rows_V_c22_dout,
        if_empty_n => img_1_rows_V_c22_empty_n,
        if_read => Mat2AXIvideo_U0_img_rows_V_read);

    img_1_cols_V_c23_U : component fifo_w11_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Merge_U0_dst_cols_V_out_din,
        if_full_n => img_1_cols_V_c23_full_n,
        if_write => Merge_U0_dst_cols_V_out_write,
        if_dout => img_1_cols_V_c23_dout,
        if_empty_n => img_1_cols_V_c23_empty_n,
        if_read => Mat2AXIvideo_U0_img_cols_V_read);

    start_for_Merge_U0_U : component start_for_Merge_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_Merge_U0_din,
        if_full_n => start_for_Merge_U0_full_n,
        if_write => Block_proc_U0_start_write,
        if_dout => start_for_Merge_U0_dout,
        if_empty_n => start_for_Merge_U0_empty_n,
        if_read => Merge_U0_ap_ready);

    start_for_Split_U0_U : component start_for_Split_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_Split_U0_din,
        if_full_n => start_for_Split_U0_full_n,
        if_write => AXIvideo2Mat_U0_start_write,
        if_dout => start_for_Split_U0_dout,
        if_empty_n => start_for_Split_U0_empty_n,
        if_read => Split_U0_ap_ready);

    start_for_GaussiajbC_U : component start_for_GaussiajbC
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_GaussianBlur162_U0_din,
        if_full_n => start_for_GaussianBlur162_U0_full_n,
        if_write => Split_U0_start_write,
        if_dout => start_for_GaussianBlur162_U0_dout,
        if_empty_n => start_for_GaussianBlur162_U0_empty_n,
        if_read => GaussianBlur162_U0_ap_ready);

    start_for_GaussiakbM_U : component start_for_GaussiakbM
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_GaussianBlur163_U0_din,
        if_full_n => start_for_GaussianBlur163_U0_full_n,
        if_write => Split_U0_start_write,
        if_dout => start_for_GaussianBlur163_U0_dout,
        if_empty_n => start_for_GaussianBlur163_U0_empty_n,
        if_read => GaussianBlur163_U0_ap_ready);

    start_for_GaussialbW_U : component start_for_GaussialbW
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_GaussianBlur_U0_din,
        if_full_n => start_for_GaussianBlur_U0_full_n,
        if_write => Split_U0_start_write,
        if_dout => start_for_GaussianBlur_U0_dout,
        if_empty_n => start_for_GaussianBlur_U0_empty_n,
        if_read => GaussianBlur_U0_ap_ready);

    start_for_Mat2AXImb6_U : component start_for_Mat2AXImb6
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_Mat2AXIvideo_U0_din,
        if_full_n => start_for_Mat2AXIvideo_U0_full_n,
        if_write => Merge_U0_start_write,
        if_dout => start_for_Mat2AXIvideo_U0_dout,
        if_empty_n => start_for_Mat2AXIvideo_U0_empty_n,
        if_read => Mat2AXIvideo_U0_ap_ready);




    AXIvideo2Mat_U0_ap_continue <= ap_const_logic_1;
    AXIvideo2Mat_U0_ap_start <= ap_const_logic_1;
    Block_proc_U0_ap_continue <= ap_const_logic_1;
    Block_proc_U0_ap_start <= ap_const_logic_1;
    GaussianBlur162_U0_ap_continue <= ap_const_logic_1;
    GaussianBlur162_U0_ap_start <= start_for_GaussianBlur162_U0_empty_n;
    GaussianBlur162_U0_start_full_n <= ap_const_logic_1;
    GaussianBlur162_U0_start_write <= ap_const_logic_0;
    GaussianBlur163_U0_ap_continue <= ap_const_logic_1;
    GaussianBlur163_U0_ap_start <= start_for_GaussianBlur163_U0_empty_n;
    GaussianBlur163_U0_start_full_n <= ap_const_logic_1;
    GaussianBlur163_U0_start_write <= ap_const_logic_0;
    GaussianBlur_U0_ap_continue <= ap_const_logic_1;
    GaussianBlur_U0_ap_start <= start_for_GaussianBlur_U0_empty_n;
    GaussianBlur_U0_start_full_n <= ap_const_logic_1;
    GaussianBlur_U0_start_write <= ap_const_logic_0;
    INPUT_STREAM_TREADY <= AXIvideo2Mat_U0_INPUT_STREAM_TREADY;
    Mat2AXIvideo_U0_ap_continue <= ap_const_logic_1;
    Mat2AXIvideo_U0_ap_start <= start_for_Mat2AXIvideo_U0_empty_n;
    Mat2AXIvideo_U0_start_full_n <= ap_const_logic_1;
    Mat2AXIvideo_U0_start_write <= ap_const_logic_0;
    Merge_U0_ap_continue <= ap_const_logic_1;
    Merge_U0_ap_start <= start_for_Merge_U0_empty_n;
    OUTPUT_STREAM_TDATA <= Mat2AXIvideo_U0_OUTPUT_STREAM_TDATA;
    OUTPUT_STREAM_TDEST <= Mat2AXIvideo_U0_OUTPUT_STREAM_TDEST;
    OUTPUT_STREAM_TID <= Mat2AXIvideo_U0_OUTPUT_STREAM_TID;
    OUTPUT_STREAM_TKEEP <= Mat2AXIvideo_U0_OUTPUT_STREAM_TKEEP;
    OUTPUT_STREAM_TLAST <= Mat2AXIvideo_U0_OUTPUT_STREAM_TLAST;
    OUTPUT_STREAM_TSTRB <= Mat2AXIvideo_U0_OUTPUT_STREAM_TSTRB;
    OUTPUT_STREAM_TUSER <= Mat2AXIvideo_U0_OUTPUT_STREAM_TUSER;
    OUTPUT_STREAM_TVALID <= Mat2AXIvideo_U0_OUTPUT_STREAM_TVALID;
    Split_U0_ap_continue <= ap_const_logic_1;
    Split_U0_ap_start <= start_for_Split_U0_empty_n;
    Split_U0_start_full_n <= (start_for_GaussianBlur_U0_full_n and start_for_GaussianBlur163_U0_full_n and start_for_GaussianBlur162_U0_full_n);

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    ap_sync_continue <= ap_const_logic_0;
    start_for_GaussianBlur162_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_GaussianBlur163_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_GaussianBlur_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_Mat2AXIvideo_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_Merge_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_Split_U0_din <= (0=>ap_const_logic_1, others=>'-');
end behav;
